### ISSUE TITLE
Verify all the packages are restored before running 'nuget.exe update'

### ISSUE THREAD

**Issue by CrispyDrone** [NuKeeperDotNet/NuKeeper#1006]
## 🐛 Bug Report

NuKeeper throws an exception when it tries to update packages. Before this, there are several mentions of "Cannot determine the packages folder to restore NuGet packages. Please specify either -PackagesDirectory or -SolutionDirectory.". See https://github.com/NuKeeperDotNet/NuKeeper/issues/72 ?

Here are the logs when run using `v -D`

[nukeeper-1.log](https://github.com/NuKeeperDotNet/NuKeeper/files/4977644/nukeeper-1.log)

The repository uses the new `PackagesReference` format, but does not have the new SKD-style csproj format. Maybe that has something to do with it. I will try to confirm this when I have some time.

It also has the following `nuget.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="DependencyVersion" value="HighestMinor" />
  </config>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="particular myget.org" value="https://www.myget.org/F/particular/" />
  </packageSources>
</configuration>
```

### Expected behavior

Packages are restored, and updated.

### Reproduction steps

1. have a non-SDK style repo with PackageReferences (?)
2. run the `nukeeper repo <url> <pat> -v D` command
3. Nuget restore and subsequently nuget update fails

### Configuration

**Version:** 0.33.0

**Platform if applicable:** 
- [X] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CrispyDrone** [comment]
I'm experiencing this problem for another repository. This second repository has a custom `nuget.config` file that changes the location of the packages folder using the `repositoryPath` configuration key.

However, I tried to set the variable `NUGET_PACKAGES`  (see https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file) to a shared location, but still receive the same exception.

**Comment by CrispyDrone** [comment]
Also, I can confirm that issue I described in the original post is related to nuget update not yet working for projects using `PackageReference`s. See https://github.com/NuGet/Home/issues/4103

**Comment by CrispyDrone** [comment]
Bump.

**Comment by iggsn** [comment]
Same here. I am not cleaning sources at all. Also I can run the DevOps pipeline a second time. But then the restore worked and I stuck with: 

Git checkout new branch 'nukeeper-update-3-packages-C9E5BCFE867B87305EED1B0A7B080850'
Updates failed NameConflictException : failed to write reference 'refs/heads/nukeeper-update-3-packages-C9E5BCFE867B87305EED1B0A7B080850': a reference with that name already exists.

So on the first run, it was not waiting for the restore and on the following run it blames the repository already exist. But it is not there.
