### ISSUE TITLE
target-branch argument for azure devops client doesn't work

### ISSUE THREAD

**Issue by kwlin** [NuKeeperDotNet/NuKeeper#1078]
## 🐛 Bug Report

After providing the targetbranch argument for the platform AzureDevops, NuKeeper keep checking against the default branch of the repo.

I've fixed the issue in PR #1077 

### Expected behavior
What described is in PR #1074 

### Reproduction steps
Provide the --targetBranch argument against the Azure DevOps git repo and see that NuKeeper will check dependencies against the default configured branch instead of the targetBranch.

### Configuration

**Version:** 0.34.0

**Platform if applicable:** 
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [x] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by kwlin** [comment]
Hmm, there is a pull request available but can't find anyone to accept it.

**Comment by MartinDemberger** [comment]
Is there anyone out there that can approve the PR so this blocking bug can be fixed?
