### ISSUE TITLE
Add indication if a pr was sumbitted or not

### ISSUE THREAD

**Issue by eladmotola** [NuKeeperDotNet/NuKeeper#1079]
## 🚀 Feature Requests

I would like to have an indication to the build ecosystem when a pr was submitted or not

### Contextualize the feature

In a CI process, if a pr was submitted i would like to send an alert to slack 

### Describe the feature

Add a flag that indicated if a pr was submitted or not

### Platforms affected (mark all that apply)
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [X] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CrispyDrone** [comment]
From what I can tell this sounds like a feature request for the azure devops extension? See https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension

**Comment by eladmotola** [comment]
@CrispyDrone  oh my bad!
can you move the issue?
