### ISSUE TITLE
Documentation improvement/receipe

### ISSUE THREAD

**Issue by phatcher** [NuKeeperDotNet/NuKeeper#1080]
## 🏗 Enhancement Proposal

Just an update to either the recipes or config pages of how to natively access secured Azure DevOps feeds

### Pitch

Had to do this again on a new machine and took a bit of hunting to find all the necessary bits...

Symptom is a not authorized error message when running nukeeper against project, no nuget.config is present...

1. Install the [artifacts credential provider](https://github.com/microsoft/artifacts-credproviderl)
2. Clear the local nuget caches, otherwise you will pick up versions that VS has already downloaded  `nuget locals all -clear`
3. Restore the packages `dotnet restore --interactive` this will prompt for device authorization and store the PAT securely
4. Now run `nukeeper` as usual and it will pick up the credentials from the store.

### Platforms affected (mark all that apply)
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by MarcBruins** [comment]
Please make a PR and extend the docs where applicable
