### ISSUE TITLE
Handle package restrictions

### ISSUE THREAD

**Issue by phatcher** [NuKeeperDotNet/NuKeeper#1081]
## 🚀 Feature Requests

Currently the package parser cannot handle package restrictions e.g.

`Skipping package 'Unity' with version range '[4.0.1, 5.0.0)' that is not a single version in file 'C:\Devel\Sample\Code\Sample\Sample.Unity.csproj'`

This means that acquiring security patches etc still has to be done manually.

### Contextualize the feature

Would allow all types of patching to occur automatically

### Describe the feature

1. Parser should break out the range into low/high values
2. High value should be used as a restriction, on the allowable package change within the context of the requested update type i.e. Patch, Minor, Major
3. Changes need to be applied on a project rather than solution level so we keep the constraints, probably should wait on #912/913

### Platforms affected (mark all that apply)
- [x] :hammer_and_wrench: NuKeeper CLI
- [x] :sparkles: GitHub
- [x] :robot: AzureDevops
- [x] :checkered_flag: Bitbucket
- [x] :earth_americas: Gitlab
- [x] :tv: Gitea
- [x] :whale: Docker

**Comment by MarcBruins** [comment]
Hi Phatcher, can you make a PR to support this?

**Comment by phatcher** [comment]
@MarcBruins Sure, I'll have a go
