### ISSUE TITLE
Could not execute dotnet restore on project names with spaces 

### ISSUE THREAD

**Issue by kwlin** [NuKeeperDotNet/NuKeeper#1091]
## 🐛 Bug Report

We are using NuKeeper on a solution with a project name with spaces. Only the NuKeeper fail while executing dotnet restore with following message:

```
dotnet restore 07 - Implementation.csproj 
Command dotnet failed with exit code: 1

MSBUILD : error MSB1008: Only one project can be specified.
Switch: Implementation.csproj

For switch syntax, type "MSBuild -help"



Updates failed NuKeeperException : Command dotnet failed with exit code: 1

MSBUILD : error MSB1008: Only one project can be specified.
Switch: Implementation.csproj

For switch syntax, type "MSBuild -help"
```

### Expected behavior
NuKeeper should accept project file names with spaces in it and use quotation while executing dotnet restore.

### Reproduction steps
Execute NuKeeper on a solution with spaces in the csproj name. 

### Configuration

**Version:** 0.34.0

**Platform if applicable:** 
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by kwlin** [comment]
The issue seems here: https://github.com/NuKeeperDotNet/NuKeeper/blob/9c14d8bfce6239218c87bd2fe6d8bc3f98892fa6/NuKeeper.Update/Process/DotNetUpdatePackageCommand.cs#L44

**Comment by kwlin** [comment]
Can anyone review & accept my PR #1093 to fix this issue

**Comment by skolima** [comment]
The PR has been merged. Thanks!
