### ISSUE TITLE
"branchnametemplate" Argument not working on DevOps Extension 

### ISSUE THREAD

**Issue by Bene2205** [NuKeeperDotNet/NuKeeper#1092]
## 💬 Questions and Help

Hi, 

do you have any idea, why the "branchnametemplate" Argument is not available via Azure Devops. 
We are getting the following Error: 
![image](https://user-images.githubusercontent.com/37846690/110086145-4c13df00-7d92-11eb-8816-425fe3435db2.png)

I would assume that the old Argument "branchnameprefix" will work. 

Thanks and BR, 
Bene

**Comment by CrispyDrone** [comment]
There is a separate repository for the Azure Devops Extension: https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension

Which version does the task use? There is an open issue there about the extension using an older version by default https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/issues/62

**Comment by MartinDemberger** [comment]
The reason might be documented in https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/issues/62

**Comment by jameskramer** [comment]
Somewhat related. I have tried many combinations to get the --branchnametemaplate working but no success. Am I not using this correctly? --branchnametemplate "ASCST-82/{Default}". This is in Azure Devops, I am forcing version 0.34.0 to be used. Apologies if this is the wrong thread, this is my first time posting to Github...
![image](https://user-images.githubusercontent.com/32177624/112541181-1787b780-8d81-11eb-8523-1300ccdd6e6a.png)

**Comment by CrispyDrone** [comment]
@jameskramer `ASCST-82/{Default}` should be valid. `ASCST-36-{Default}` isn't for some reason; the regex that's used for validating a git branch name doesn't make much sense to me.

**Comment by jameskramer** [comment]
@CrispyDrone I agree. The [regex](https://github.com/NuKeeperDotNet/NuKeeper/blob/c189fdaa0a276bcb31f53a77b56168deacb6bd0b/NuKeeper/Commands/CommandBase.cs#L310) looks rather complicated. And like you said, it does not seem to work correctly.
