### ISSUE TITLE
Code coverage batch not working

### ISSUE THREAD

**Issue by msallin** [NuKeeperDotNet/NuKeeper#1137]
## 🐛 Bug Report

Code coverage batch in README.md doesn't work.

**Comment by zplan** [comment]
Why?
I see the batch showing 39% and in Azure the line coverage shows 39.4%:

Azure (latest build https://dev.azure.com/nukeeper/NuKeeper/_build/results?buildId=2091&view=codecoverage-tab):
Line coverage: 39.4% (3401 of 8615)

Batch:
[![Azure DevOps coverage](https://img.shields.io/azure-devops/coverage/nukeeper/NuKeeper/4.svg)](https://dev.azure.com/nukeeper/NuKeeper/_build?definitionId=4)

**Comment by msallin** [comment]
Oh... Works again... Wasn't working when I created the issue.
