### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#128]
Some packages are best updated together, e.g. `NLog` and `NLog.Schema`, or all the `AWSSDK.*` packages.
Roll them into 1 PR.

**Comment by skolima** [comment]
Note: `Microsoft.AspNetCore.All` is  another major example here, if the individual packages are updated but not the "meta-package", the build will fail.

**Comment by daniel-munch-cko** [comment]
Just gave NuKeeper a try and it's really rad. Thanks a lot! 

Are there plans or ideas for the batching to be implemented soon? I think it would be a real useful addition. If nobody's currently working I'd be happy to give it a look.

How would you imagine such a feature? I've been thinking about either
- making it configurable, i.e. explicitly say that `AWSSDK.*` or `Microsoft.Extensions.*` should be batched
- do it automagically, i.e. find the LCD of all packages being updated from the same version towards the same version.

Thoughts?

**Comment by skolima** [comment]
Automatic detection would have to be quite clever to deal with all the cases we've seen so far - perhaps some default settings in the configuration file for the well known package sets, along with allowing the user to alter the setting to deal with internal packages that have to go in step, would be a better approach?

**Comment by AnthonySteele** [comment]
Hi.

We have no WIP on batching right now.

My preference is to use automation for this as much as possible. My thinking is that NuKeeper *is* automation, because .net devs don't manually update very well, because a tool to proactively check for and apply updates raises the game.

I'm not quite sure how, but I do know that the package info that the Nuget API returns includes dependencies. A first step would be in the ordering - if there are updates to both `AWSSDK.Core` and `AWSSDK.Lambda`, and Lambda depends on Core, then the update to Core should be sorted above the update to Lambda.

**Comment by skolima** [comment]
I've just hit another instance where this would be very useful - and where Visual Studio updater gets it wrong as well, currently. `Microsoft.AspNetCore.App` 2.1.1 rolled out recently, and with it a large group of other updates turns out e.g. those need to be updated in sync or the project won't build any more:
`Microsoft.AspNetCore.App`
`Microsoft.VisualStudio.Web.CodeGeneration.Design`
`Microsoft.AspNetCore.TestHost`
`Microsoft.Extensions.Configuration`

What makes it trickier is that, like `System.IO.Abstractions` and `System.IO.Abstractions.TestingHelpers`, some of those packages would be installed into a "main" projects and some into a test project - and they need to match.

**Comment by AnthonySteele** [comment]
> A first step would be in the ordering code - e.g. if there are updates to both AWSSDK.Core and AWSSDK.Lambda, and Lambda depends on Core, then the update to Core should be sorted above the update to Lambda.

This has been done  in #405 and works. But updating the AWS SDK packages is still a long ordered sequence of PRs, where one rollup PR is less bother and probably safer. 

There might still be cases where there are "2 or 3 PRs, both failing due to the absence of the others." as mentioned in #421

**Comment by AnthonySteele** [comment]
Closed for now due to `--consolidate` flag that provides one PR for all the selected updates. I use this with an "include" filter to update `AWSSDK.*` in one go. This is a bit more manual than I would prefer, but it works well enough.

A later thing to look into would be "inferring what to batch" which is more advanced and smaller scope.
There are "lower-hanging fruit" to work on in the meantime.
