### ISSUE TITLE
More conventional PR model with origin and upstream

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#129]
I want the option to use a more conventional Pull-request model across 2 github users.

e.g. I point Nukeeper at `https://github.com/NuKeeperDotNet/JustEat.StatsD` and it forks it to `https://github.com/NuKeeperBot/JustEat.StatsD` (if this fork does not already exist). 

We can call these `upstream` and `workarea` respectively. It should then pull from `upstream`, make changes and push a new branch to `workarea`, and PR that branch back to `upstream` . 

This is the workflow that we are used to. It has the advantage that you don't need to be able to push to `upstream` as no new branches are created there.

**Comment by AnthonySteele** [comment]
I attempted to run against `https://github.com/hibri/HttpMock` and ran into this. 
NuKeeper attempts to make branches in that repo and I don't have permission to do that - so it failed with 403 errors. 

Instead, it should follow the more usual procedure.

- detect user `NuKeeperBot` from the api token
- If a "workarea" fork of `HttpMock` under `https://github.com/NuKeeperBot/HttpMock` does not exist, create it. 
- Git pull from `upsteam` `master`
- Branch and perform updates, push the branches to `workarea`.
- Create pull requests back to upstream.

**Comment by skolima** [comment]
That's quite a bit of clever, I was just planning to create the fork manually :-) Does the token provide all the necessary information to do this?

**Comment by AnthonySteele** [comment]
If you make the fork manually and work off that, then the PR will come back to your fork.
I think that we have all the info needed in: the token, the repo being worked on and the github api base url.

**Comment by AnthonySteele** [comment]
All done, but now this needs to be controlled by an option, since some orgs internally don't use forks, just branches on 1 repo. Fair enough that's simpler and works. So Nukeepr should _not_ try to make or use a fork if the option says not to.

**Comment by skolima** [comment]
With #178 #180 #182 #183 , the control options for the feature are ready as well. Great work!
