### ISSUE TITLE
Update a specific package to a specific version

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#138]
A Feature request:

> We have an internal component, call it `Acme.Widgets`. We have just fixed bugs in it, and released a new version, `4.5.6`. We want to scan all repos in the internal github and identify those that use `Acme.Widgets` at a lower version and update them to version `4.5.6`. This will help us make our production system reliable quickly.

Notes:

* When `4.5.6` is the latest `4.x` version and all consumers are using a version `4.x`, this is the same as #126 to apply minor updates. However neither of those constraints is guaranteed.

* If some code is using `Acme.Widgets` version `1.0` which has breaking changes to `4.0`, the code may not compile or work correctly after the update to `4.0`. Fixing up the code that breaks is definitely out of scope for NuKeeper. The Nukeeper model is to make a PR, and then a build and tests and human inspection should tell you if the PR is good or not.

**Comment by TomFreeman** [comment]
To be explicit - although it is described above - this is for the situation where we know for example that version `4.5.6` is good, it's been released to production and tested, but there might be a new version `4.6.1` that hasn't yet been widely adopted (or worse has a known bug, but which is sufficiently an edge-case that the package hasn't been delisted generally.)

A paranoid developer owns a set of applications and wants to be relatively up to date with `Acme.Widgets` but wants to ensure the package has been widely adopted and found problem free.

There are two approaches one could take:

- specify an exactly equals constrain (such that the paranoid developer explicity sets the package number to `4.5.6`) This can be used by the developer to update all his applications to this version if it is applicable.
- specify a less than or not-equal constraint (such that the paranoid developer who knows `4.6.1` is bad will specify `!= 4.6.1` or `< 4.6.1`. This retains the automated nature of the updates, but allows the developer to skip, or hold off, on updates to packages they don't fully trust yet.

It's implied that have a greater-than constraint is redundant.

**Comment by AnthonySteele** [comment]
Currently I am thinking along these lines,
````csharp
    public enum UpdateLimit
    {
        None = 0, // current and default behaviour
        MinorOnly, // no major version changes, as per #126
        UpToSpecificVersion // this feature, #138
    }
````
The problem is that an `UpToSpecificVersion` setting would require a specific version, e.g. `9.0.1` and would then, unlike the other options, apply to only 1 package e.g. `NewtonSoft.Json`.

**Comment by AnthonySteele** [comment]
We have restrictions now with include regex on the package name and allowed verson change.
