### ISSUE TITLE
Need consistency between command line arguments

### ISSUE THREAD

**Issue by cohen990** [NuKeeperDotNet/NuKeeper#21]
Currently, Repository Mode accepts a repository URI and extracts the owner, repo name and github api endpoint from that.

Organisation mode however accepts organisation name and github api endpoint.

We want to standardise these

**Comment by AnthonySteele** [comment]
Also want to move away from positional args except possibly for the first mode param, and use e.g. `-token foo -repo bar`.  
Also look at  a lib for parsing these.
And values for env vars and./or config file.

**Comment by cohen990** [comment]
We've moved away from positional arguments now - see #25

**Comment by AnthonySteele** [comment]
Close or?
