### ISSUE TITLE
Assembly binding redirects, etc

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#235]
ABRs etc

The most common issue that I see inside the business with NuKeeper Prs is that an Assembly Binding Redirect is made incorrect by the update.

e.g. the config file contains:
````
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" ... />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
````

And `Newtonsoft.Json` is updated to v 11. Afterwards the code will compile, tests will pass, and after merge the code is deployed to test server, wherupon it fails totally - it won't even start, since it insists on Newtonsoft.Json v10.0.0 being present and it is not, Newtonsoft.Json V11.0.0 is present instead.

Fixing this is painstaking and automatable. 

When applying an update of package `Foo` from V1 to V2, find all config files, find in them all Assembly Binding Redirects of Foo to Foo V1, and change it to be a binding redirect to Foo V2, since we know that after this change Foo V1 will not be present, and Foo V2 will.

Do not add or remove Binding Redirects, as this may not be necessary, just update them in place.

This should be enabled by command-line option.

Should also apply to config templates, since neglecting these is another common source of error that can be automated away.

A similar thing should be done to declared dependencies in `.nuspec` files.

**Comment by skolima** [comment]
For `.nuspec`, this is required because of missing feature in `nuget pack`: https://github.com/NuGet/Home/issues/6698
For Assembly Binding Redirects, this related dotnet issue is https://github.com/dotnet/sdk/issues/1351 and for msbuild https://github.com/Microsoft/msbuild/issues/1310

**Comment by AnthonySteele** [comment]
More and more I hope that this will be solved by projects just stopping using explicit binding redirects any more.  They're not there in NetCore, and in full framework, [you can do it automatically]( https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions#relying-on-automatic-binding-redirection).

This might be the preferred approach, and can be documented  as such.

**Comment by AnthonySteele** [comment]
Closed as out of scope and won't be developed any time soon. "automatic binding redirection" is preferred.

**Comment by AnthonySteele** [comment]
An attempt was made in #237, which highlighted the difficulties of doing this in NuKeeper.
