### ISSUE TITLE
Needs a CI build

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#24]
On appveyor and/or travis
as per https://github.com/justeat/NLog.StructuredLogging.Json/ appveyor.yml / .travis.yml

**Comment by cohen990** [comment]
travis works just fine for dot net core. See https://github.com/cohen990/EasyConfig.Net.Core/blob/master/.travis.yml

**Comment by AnthonySteele** [comment]
Now has travis
