### ISSUE TITLE
dotnet update fails on linux

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#257]
I get this output from an unattended job intended to self-update
````
dotnet update package SimpleInjector in path /tmp/NuKeeper/15c39f8d83d149e8bc52eddfe3870764/NuKeeper NuKeeper/NuKeeper.csproj
Update failed Exception : Exit code: 1

MSBUILD : error MSB1009: Project file does not exist.
Switch: NuKeeper/NuKeeper.csproj
````
so it looks like 
- it' using the temp folder `/tmp/NuKeeper/15c39f8d83d149e8bc52eddfe3870764/`
- it's trying to update `./NuKeeper/NuKeeper.csproj` but 
- there's an extra `NuKeeper` in the middle when these paths are joined? or maybe a missing `./`

**Comment by skolima** [comment]
Is this still valid, with #265 created?

**Comment by AnthonySteele** [comment]
Fixed in https://github.com/NuKeeperDotNet/NuKeeper/pull/258
Is working now
