### ISSUE TITLE
Doesn't work with final release of dotnet 2.1

### ISSUE THREAD

**Issue by darickc** [NuKeeperDotNet/NuKeeper#284]
I am getting an error:

It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-rc1' was not found.

I installed from Nuget.

**Comment by AnthonySteele** [comment]
Do you have the NetCore 2.1 release version installed?
We are going to move from the RC to that very soon [with this PR](https://github.com/NuKeeperDotNet/NuKeeper/pull/283)

But travis Ci build support is not there yet.

**Comment by AnthonySteele** [comment]
Hello. travis have now gone live with their NETCore 2.1 final release support.
We have updated to NETCore 2.1 final release 
I have pushed a new version of NuKeeper to https://www.nuget.org/packages/NuKeeper/0.1.0
It should be live soon, but somethings this takes as long as a couple of hours.

**Comment by darickc** [comment]
I've updated it and it is working.  Thanks.
