### ISSUE TITLE
Update a local project/solution

### ISSUE THREAD

**Issue by darickc** [NuKeeperDotNet/NuKeeper#286]
Thanks for the tool.  

Are there any plans to be able to update a local project/solution instead of just inspect it?  We don't use Github for our repositories, we use an on premise TFS git repo.  It would be nice to be able to just update the local project and then push that myself.

**Comment by AnthonySteele** [comment]
yes, we are planning a `mode=update` to perform updates locally as a next step after `inspect` mode.

**Comment by darickc** [comment]
Awesome,  thanks.

**Comment by AnthonySteele** [comment]
I am going to bring this back as a place to talk about how local update mode might work.

When nukeeper is run against a repo and it detects 2 possible updates, two pull requests are made, each from a separate branch. The source control mechanisms are used to keep these changes separate.

But in a purely local update, we do not use any source control system. So we either apply multiple package updates to the same working files, or stop after the first one. We either automatically select the a good candidate using the existing sort, or ask the user to choose.

**Comment by AnthonySteele** [comment]
The MVB would be to update 1 automatically chosen package, then exit. This is a good first step as it involves a new mode, moving some code around, and associated tests.

**Comment by skolima** [comment]
TBH, interactive mode seems a bit... redundant? If you've got a local clone and want to update the packages interactively, most times you'd just run VS, unless your solution is so heavy that this becomes a problem.
Updating all packages in a local folder with `packages.config` is a scenario mostly covered by `nuget update` - however, there's no `dotnet` equivalent, so it might be useful to have in NuKeeper.
The "apply first update found then exit" mode might be the one most handy :-)

**Comment by AnthonySteele** [comment]
I agree, the best plan is to make easy things that are hard using the existing tools. Mostly around "just run it and updates happen" with few clicks and decision.

**Comment by AnthonySteele** [comment]
Basics are done
