### ISSUE TITLE
Logo Proposal for NuKeeper

### ISSUE THREAD

**Issue by area55git** [NuKeeperDotNet/NuKeeper#322]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project NuKeeper.

I will be pleased to collaborate with you.

**Comment by area55git** [comment]
Following the graphical line of NuGet I present this proposal

[![PROPUESTA_LOGO_Nu_Keeper.jpg](https://s8.postimg.cc/dj301xmf9/PROPUESTA_LOGO_Nu_Keeper.jpg)](https://postimg.cc/image/pxps29dxd/)

If you like I can send you the files in PNG, SVG or any format you need.

**Comment by AnthonySteele** [comment]
Hello

Thanks!

For context, the current icon that I use [for the NuKeeperBot account](https://github.com/NuKeeperBot) is not worth keeping - It's just the NuGet logo and a "robot face" emoji pasted together by me. 
And something better would be nice and we would definitely give credit where it's due.

So, the proposed logo is very similar to the https://www.nuget.org/ logo, with the diagonal line from top left to bottom right, and circles + squares. This is actually good, so long as it's not too similar.

If I was to add one thing, I want to keep the idea of "automation". I don't know how you represent that in a logo though.

**Comment by area55git** [comment]
Generally the concept of automation is represented by a gear or a robotic arm.

What do you think of these proposals?

[![PROPUESTA_LOGO_Nu_Keeper.jpg](https://s33.postimg.cc/szb51pc1r/PROPUESTA_LOGO_Nu_Keeper.jpg)](https://postimg.cc/image/bm0umugqj/)

**Comment by AnthonySteele** [comment]
I like the second one with the gear. The first seems to have too many "moving parts".

**Comment by area55git** [comment]
Perfect, I will prepare the files in various formats (SVG, PNG, JPG and others)
I will send you a link in GoogleDrive and I will make a PR to place the logo in the Readme folder and merge it.

**Comment by area55git** [comment]
Hi @AnthonySteele, What color option do you like?

[![PROPUESTA_LOGO_Nu_Keeper.jpg](https://s33.postimg.cc/xtszav8tr/PROPUESTA_LOGO_Nu_Keeper.jpg)](https://postimg.cc/image/5gxhken3f/)

**Comment by AnthonySteele** [comment]
The blue at top left. Also, the other logo with the gear.

**Comment by area55git** [comment]
Hi @AnthonySteele 

[![PROPUESTA_LOGO_Nu_Keeper.jpg](https://s33.postimg.cc/yijsh9wq7/PROPUESTA_LOGO_Nu_Keeper.jpg)](https://postimg.cc/image/413xpq9d7/)

**Comment by slang25** [comment]
:heart: <span>#</span>3

**Comment by AnthonySteele** [comment]
Agreed # 3 is best!

**Comment by area55git** [comment]
I made this design for the Readme folder, do you like it?
If approved, let me know to make a PR and place it so that I can merge it

[![Readme_3.jpg](https://s33.postimg.cc/dci84q0zj/Readme_3.jpg)](https://postimg.cc/image/xjvnx0ygr/)

**Comment by area55git** [comment]
### [FILE DOWNLOAD](https://drive.google.com/open?id=1l9F4ece1tPaRfA8zjwWr_24niK06mZbV)

[![derechos.jpg](https://s33.postimg.cc/pr50575e7/derechos.jpg)](https://postimg.cc/image/bxgng5csr/)
This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

**Comment by AnthonySteele** [comment]
I away the PR!

I have made a folder called "Logo". Not sure why though? Your PR could have done that.

**Comment by AnthonySteele** [comment]
ok, we're ready ;)

**Comment by slang25** [comment]
@area55git assuming you are new to git/GitHub:
1. Use git command line to clone your fork:
```
git clone https://github.com/area55git/NuKeeper.git
```
2. Make and checkout a branch locally:
```
git checkout -b logo
```

3. Make your changes
4. Add your changed files and commit:
```
git add -A
git commit -m 'Add logo'
```

5. Push your changes:
```
git push -u origin logo
```

Goto Github.com and click the pull request button.

**Comment by area55git** [comment]
PR #371 
I could not upload the files to the "Logo" folder, excuse me but I do not know how to do it. I just made the change in the Readme folder.

**Comment by AnthonySteele** [comment]
I have added those files to the `/Logo/` folder. Named `NuKeeperTopBar.jpg` and `NuKeeperBottomBar.jpg`.
Also the `.svg` file is stored there. Can you adjust paths in your PR?

**Comment by area55git** [comment]
That's enough for my portfolio, just merge the PR, thank you very much for allowing my contribution in your project. If you need a logo for another Repository you can contact me.

**Comment by AnthonySteele** [comment]
Merged and looking good! 
Thank you so much!
Do you want any text at the bottom, e.g. "logo by @area55git, licensed under a Creative Commons Attribution 4.0 International License." ?

**Comment by area55git** [comment]
Yes..!! I would appreciate it

**Comment by AnthonySteele** [comment]
Done. Thanks again!
