### ISSUE TITLE
Gitlab Integration

### ISSUE THREAD

**Issue by reaction1989** [NuKeeperDotNet/NuKeeper#327]
ATM there is only a GitHub Integration. 

Having an GitLab MR Integration would open the door for many more users

**Comment by AnthonySteele** [comment]
This would be a useful feature. The hard part would probably be in the project organisation and appropriate interfaces and DTOs to handle either GitHub or GitLab or other integrations.

**Comment by SeriousM** [comment]
May I add the request to support VSTS GIT Repositories?
This would be awesome!!

**Comment by AnthonySteele** [comment]
If they have an API that we can work to do equivalent things to the github api, then this is all possible.

**Comment by lxalln** [comment]
There is a full API for GitLab.

[GitLab Merge Request API docs](https://docs.gitlab.com/ee/api/merge_requests.html)

**Comment by phatcher** [comment]
@AnthonySteele Is it worthwhile to try and spec this out or should I just dive in and attempt something?

The best approach I can see is to work on VSTS/GitLab specific APIs and then lift out commonality once each of these is working.  Advantage of this is we don't disrupt the development/maintenance of the main code line whilst this is going on.

**Comment by slang25** [comment]
@AnthonySteele It might be worth adopting an "up for grabs" label for these issues

**Comment by AnthonySteele** [comment]
True, I won't be able to work on VSTS integration since I have no VSTS to integrate with, so it is "up for grabs". 

I expected the first step is to introduce some abstractions that could be implemented by github and also by VSTS, gitlab etc and so decouple a lot of the code from the specifics of the guthub impl 

If it's possible, i would suggest trying to make a "VSTS Integration" project, trying to get some commonality with github.

**Comment by AnthonySteele** [comment]
Similar to #336 - supporting one of VSTS / Gitlab should help the other

**Comment by MarcBruins** [comment]
We have support now for VSTS, BitBucket and  Github, adding this shouldn't be hard.

**Comment by zubivan** [comment]
Hi all, I picked it up. Will create a pull request with initial structure.

**Comment by zubivan** [comment]
Looks like we can close this one? @MarcBruins @AnthonySteele

**Comment by MarcBruins** [comment]
You are right @zubivan, thanks for the notice!
