### ISSUE TITLE
fuget.org integration

### ISSUE THREAD

**Issue by SeriousM** [NuKeeperDotNet/NuKeeper#332]
Hi!
Is it possible to add a link to the pull requests where an api diff can be inspected?
Fuget is a service to inspect nuget packages and they provide api diffs, something like this:
https://www.fuget.org/packages/Newtonsoft.Json/11.0.2/lib/netstandard2.0/diff/9.0.1/
What's your opinion about it?

**Comment by AnthonySteele** [comment]
Hello. Yes, fuget is nice. 

I think what you are suggesting is that e.g. when NuKeeper generates a PR updating `Newtonsoft.Json` from `9.0.1` to `11.02`, it should also generate the link above? That's possible, it would go in `CommitWording.cs` along with the `NugetPackageLink`

**Comment by skolima** [comment]
There's a catch there - those links aren't trivial to generate, as there's target platform embedded in them. NuKeeper doesn't handle this information at the moment.
