### ISSUE TITLE
Consider updating to LibGit2Sharp 0.26.0-preview-0027

### ISSUE THREAD

**Issue by bording** [NuKeeperDotNet/NuKeeper#333]
I noticed the following in your documentation:

>Also, not all linux distributions are supported by LibGit2Sharp, which is a c# wrapper for the platform-specific binaries of LibGit2.

I just wanted to point out that as of LibGit2Sharp 0.26.0-preview-0027, we should now support all the linux distros that .NET Core 2.1 is supported on.

If you do find a distro that doesn't work, please file an issue, because I now have the infrastructure in place to easily add another native library to LibGit2Sharp.NativeBinaries.

**Comment by skolima** [comment]
Welcome! Thanks for pointing this out.

Two scenarios we've hit so far were Amazon Linux and default Microsoft Docker .NET Core 2.1 images #305
There's a workaround available for both, so most likely we'll wait for a stable release.

**Comment by bording** [comment]
I understand, though there's nothing to really be concerned about regarding it being a prerelease. I'm not sure when we'll be releasing 0.26.0.

**Comment by bording** [comment]
That's a good question, one that I don't have a great answer for. I'm not really the one who decides on when to put out new releases, but from what I've seen there tends to be a desire for there to be "enough" new stuff before having a new release.

**Comment by bording** [comment]
I understand SemVer quite well! 😄

Since NuKeeper is a .NET global tool, the package has no external dependencies, so the version of LibGit2Sharp you're referencing internally would not alter anything about the way you need to version your package. Also, you're not a library, so no one else would be taking a dependency on your package, so SemVer matters a lot less in that scenario.

Anyway, my intention of opening this issue wasn't to start a argument, and it certainly wasn't intended to try and tell you how to maintain your project. I just wanted to let you know that that you can support more linux distros by updating the package!

**Comment by AnthonySteele** [comment]
This is still the latest build of libgit2sharp: https://www.nuget.org/packages/LibGit2Sharp/0.26.0-preview-0027

**Comment by AnthonySteele** [comment]
Done
