### ISSUE TITLE
Updating package references changes the order of packages in the csproj file

### ISSUE THREAD

**Issue by jonnii** [NuKeeperDotNet/NuKeeper#337]
Updating package references in a `csproj` file can changes the order of the referenced projects which in turn can lead to merge conflicts and additional line noise. For example:

```
<ItemGroup>
  <PackageReference Include="A" />
  <PackageReference Include="B" />
  
  <!-- a comment -->
  <PackageReference Include="ThePackageToUpgrade" />
</ItemGroup>
```

will result in:

```
<ItemGroup>
  <PackageReference Include="A" />
  <PackageReference Include="B" />
  <PackageReference Include="ThePackageToUpgrade" />
  
  <!-- a comment -->
</ItemGroup>
```

I believe this is a side effect of removing the package reference and re-adding it (in `DotNetUpdatePackageCommand`). I think you should be able to use `add` to update if the version is specified, however I'm not an expert on doing this programatically.

Let me know if you need any more info.

**Comment by skolima** [comment]
That would be neat, there's a problem, though. While this works for dotnetcore projects, currently it breaks .NET classic projects that use `<PackageReference/>` syntax. For those, not running the `dotnet remove` step results in the reference being installed twice. Test that catches this: https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper.Integration.Tests/NuGet/Process/DotNetUpdatePackageCommandTests.cs#L92

NuKeeper would need to distinguish between those two file formats in order for this to work.

**Comment by AnthonySteele** [comment]
The `PackageReferenceType` should tell you how the reference works.

**Comment by skolima** [comment]
Good spot. I've forgotten that we do treat the differently. PR waiting.

**Comment by jonnii** [comment]
Eagerly anticipating the next release so I can try it out again!

**Comment by AnthonySteele** [comment]
The way that the commandline options works is all changed in the next version.
