### ISSUE TITLE
Local config.json

### ISSUE THREAD

**Issue by shatl** [NuKeeperDotNet/NuKeeper#339]
Hi,
Is this possible to have local `config.json` in the directory I'm running nukeeper? 

Also, please rename config.json to something more specific (e.g. `nukeeper.json` or `nukeeper.config.json`).

P.S. Thanks for a great work done on nukeeper!

**Comment by AnthonySteele** [comment]
Hi

We're currently working on revamping settings, and the config file. These are good ideas, thanks.

**Comment by AnthonySteele** [comment]
Command-line args are all different in version `0.6`. Config file support might come back in some form, but probably using names identical to the "long name" of command line args. Which options would you use from file?

**Comment by shatl** [comment]
Hi Anthony,

* package sources;
* age;
* include / exclude masks;
* verbosity;
* label;
* api endpoint configuration;

**Comment by AnthonySteele** [comment]
I am having a look at reading settings from a `nukeeper.config.json` file in the current directory.

I am starting with `Include` and `Exclude` regexs, and will also look at max changes etc.

I do not see that putting pakage sources in this file is  necessary: by default, NuKeeper will read the `NuGet.config` file of the target code and take settings from there, as the build also does.

**Comment by AnthonySteele** [comment]
All the fields of this DTO are now settings that can come from the file `nukeeper.config.json` in release 0.7: 

https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper/Configuration/FileSettings.cs

And will work as the same-named commandline option.

This covers all the options listed above, with the exception of package sources. These should come from `NuGet.config` instead.

Better docs will follow in the next few days.

**Comment by shatl** [comment]
Thanks a lot, works for me
