### ISSUE TITLE
Create communication channel for NuKeeper

### ISSUE THREAD

**Issue by cohen990** [NuKeeperDotNet/NuKeeper#34]
Potentially slack or whatever - potentially we can just use github's infrastructure to communicate but it could be handy to have discussions through slack or gitter or something like that

**Comment by AnthonySteele** [comment]
Agreed. Gitter might be a good venue for this.

**Comment by AnthonySteele** [comment]
This exists now: https://gitter.im/NuKeeperDotNet/Lobby
