### ISSUE TITLE
Long form config values not being applied

### ISSUE THREAD

**Issue by jonnii** [NuKeeperDotNet/NuKeeper#340]
I have found that certain config variables (e.g. `max_pull_requests_per_repository`) do not get applied when run in `repository` mode. They do, however, work when using the short version - `maxpr` in this case.

**Comment by AnthonySteele** [comment]
We are currently revamping commandline args and config. Goals are

* it should work as similarly as possible to `dotnet` utilities. We're going to use same `CommandlineUtils` library
* it should have consistent naming and understandable output. So reporting when options or config settings are not read is useful?

You are using the config file? I assume that support for this file is important?

**Comment by AnthonySteele** [comment]
Command-line args are all different in version `0.6`. Can you try with this version and get back to us?
If you have used options in a file, which ones? Config file support might come back in some form, but probably using names identical to the "long name" of command line args.

**Comment by jonnii** [comment]
no longer an issue for me.
