### ISSUE TITLE
Ability to filter by "category" in org mode

### ISSUE THREAD

**Issue by jonnii** [NuKeeperDotNet/NuKeeper#341]
When running in org mode if you find yourself sharing an org with other teams who may not want to necessarily have nukeeper run on their repositories (shame on them!) or if you have a legacy code base for which nukeeper should be excluded because otherwise Chaos™️ then it would be nice if you could have a repository "opt-in" to having nukeeper applied perhaps by using a github repository label.

**Comment by cookie1981** [comment]
@jonnii recent updates have added filters using regex. Check the updated docs for excluderepos and includerepos. These work against the `org ` command. (Check out the updated docs: https://github.com/NuKeeperDotNet/NuKeeper/wiki/Configuration) 
Maybe not the solution you are after, but should help limit the impact of the problem.

**Comment by jonnii** [comment]
This doesn't quite work for us as we share an org with many other teams and there's no way to apply a regex to isolate just our own repos.

**Comment by AnthonySteele** [comment]
I am having a quick look at this again. Do repositories actually have labels/tags or some easy way to mark them? I am thinking that it could be an "opt in" if there is an easy way to do it? Issues like this one have labels, but repos?

**Comment by jonnii** [comment]
They do, if you view one of your own repositories underneath the description you'll see a link that says "manage topics". We have a powershell script which finds all repositories with a given topic (we use `nukeepered`) and then runs `nukeeper` against them. 

I just did a check to see if octokit supports topics (it does not), there's a pull request pending though: https://github.com/octokit/octokit.net/pull/1721

**Comment by AnthonySteele** [comment]
We will need octokit support, so will revisit when https://github.com/octokit/octokit.net/issues/1707 or https://github.com/octokit/octokit.net/pull/1721 or similar lands.

I can see myself using this filter, as I could setup nukeeper jobs in-house, and get repos to opt-in by tagging.

"topics" is not quite the same as "labels" though. I could label an issue with "up for grabs", "feature" or basically anything. "topics" seems more constrained to metadata describing the repo's function, for search purposes.
