### ISSUE TITLE
Support for updating more than 1 package per run in Update mode

### ISSUE THREAD

**Issue by mrrobdlon** [NuKeeperDotNet/NuKeeper#368]
Currently the docs state that in Update mode ["Only one update is applied per run."](https://github.com/NuKeeperDotNet/NuKeeper/wiki/Configuration#update-mode)

It would be great to be able to update all packages that match the filter criteria in a single run.

**Comment by AnthonySteele** [comment]
Hello

We are preparing for V0.6, which completely revamps the command line options.

After that, this area is worth looking at.

I would hesitate to just" run them all" in every case - I have seen solutions with 50+ outdated packages, and updating them all at once is guaranteed to break something.

Because want safety, there should be a limit on it, like `--maxpr`.

**Comment by mrrobdlon** [comment]
Hi @AnthonySteele ,

Thanks for the info, it's very much appreciated. I'll get 0.6 and have a play with it as soon as it's available, unfortunately I don't have time to build the latest.

Here's a bit of feedback on what I'm trying to achieve.

The use case that I'm going for pertains to packages from an internal source. I know that I've published, for e.g. 6 updated packages, that are all in the namespace MyAwesomeApp.Foo. Now I want to update all packages in MyAwesomeApp.Foo.* in all other solutions in my system.

In this case I don't really have a risk of taking updates that I'm not expecting, and if they break the build then that's what I want so that I can fix it. What I don't want to have to do is run the command 6 times on each of the solutions (somewhere from 3 to 10). I'm not particularly bothered about how long it takes but I'd like it to be a single command so that I can get on with something else while it runs.

Thanks again,
Rob.

**Comment by skolima** [comment]
Ha! This works currently, IF you have your projects on GitHub, in an Organisation - I'm using this quite often and I guess that one of the main use cases for @AnthonySteele as well . However, for on-disk update, that's something that will need to be added.

**Comment by AnthonySteele** [comment]
Now I slightly regret calling the existing setting `MaxPR` instead of `MaxChanges` - if it was `MaxChanges` then it could be used the local update context.

**Comment by skolima** [comment]
We've got a breaking changes release coming out, it's not too late yet to rename it. Although, with `MaxChanges` in context of GitHub updates, it would be somewhat confusing what it refers to - updated project count? Package count? PR count per repo? PR count over the whole run? (Would need better naming)

**Comment by AnthonySteele** [comment]
Or it could mean "max packages changed per PR". yep, let's leave it be.

**Comment by AnthonySteele** [comment]
In version `0.6.2` the `update` command can now take the `--maxupdate` or `-m` option to set this to a number larger than 1.

**Comment by mrrobdlon** [comment]
Excellent, works a charm
