### ISSUE TITLE
When there are lots of packages to inspect a socket is used for each package

### ISSUE THREAD

**Issue by cg110** [NuKeeperDotNet/NuKeeper#383]
I've been trying out nukeeper against a large set of project files, which in total have ~390 unique nugets to check.

Basically running:
nukeeper inspect -v d -c patch

I've noticed that the first updates work well (however, it looks like a fresh SSL socket is consumed for every package being checked, which is quite a lot in this case)

However, second checks seem to be very much slower, especially when the data is in cache (in fact the cache is slower than checking the web server, suggesting that the cache code in the nuget api is serialized, breaking into the process suggests that the xml parsing might be locking)

So I figure that the problem is something underlying in the nuget api usage that stops socket reuse (eg is there perhaps an object in nuget that should be Idisposable (but isn't))

I noted from debugging that PackageMetadataResource from seems to have a http source hanging off it, which is generated from the owning source repository, however, there's one sourcerepository per call.

I thought I'd try and share the source repository between all users of the same packagesource.  This appears to have fixed the socket consumption, and caching problems.

It appears that making the code share one source repository per package source fixes the caching performance.  But I'm not sure if it's a "good" fix for all code paths, as it still shows the large socket usage in the uncached case of hitting the server for data.  I suspect that perhaps the internals of the nuget library aren't making the massive concurrency good

To improve the cached case, within PackageVersionsLookup.cs, add a:
```c#
using System.Collections.Concurrent;
```
And update BuildSourceRepository as:
```c#
private ConcurrentDictionary<PackageSource, SourceRepository> _sourceCache = new ConcurrentDictionary<PackageSource, SourceRepository>();
private SourceRepository BuildSourceRepository(PackageSource packageSource)
{
    return _sourceCache.GetOrAdd(packageSource,
        key => new SourceRepository(key, Repository.Provider.GetCoreV3()));
}
```

The change pass the unit tests, but I'm not sure if it's safe for general usage or not.

I'm actually surprised that the code isn't hitting a http request limit within the .net client code, so it could be I've changed/broken something in my .net config files (but I don't recall changing anything for .net core)

**Comment by skolima** [comment]
Good spot! This will need some investigation - possibly how NuGet itself is using this code could point to some mistakes we've made.

On the request limit - I'm reasonably sure dotnetcore removed those. `HttpClientHandler.MaxConnectionsPerServer` is set to `Int32.MaxValue` by default.

**Comment by cg110** [comment]
Ah, that answers why I hit the internal nuget server with so many connections :)  I've not had to use .net core that much, yet. I know that we had to tune up the numbers for .net framework from the default of 4, but normally just in api callers.

Overall this looks like a great tool, having written a posh script to try and do this, that would take 20 minutes on the 300+ projects (as it ran nuget.exe on every proj file), this takes far less time to inspect.  And compared to Visual studio, that was 2-3 hours to do the nuget updates....

**Comment by AnthonySteele** [comment]
I am going to try a variation on this fix. I think it's better to make the `PackageSource` -> `SourceRepository` map upfront. In many cases it will contain only 1 element, and even with internal sources, there will only be 2 or 3 of them most times.

**Comment by AnthonySteele** [comment]
@cg110 Are you set up to run the source code of a PR? I hope that #384 fixes the cache performance by reusing `SourceRepository` instances across parallel calls to  `PackageVersionsLookup` - it's basically your code and is IMHO safe.

I assume that "~390 unique nugets" means 390 _packages_ from a handful of internal and public package sources?

**Comment by AnthonySteele** [comment]
Change has been merged

**Comment by cg110** [comment]
Ok, I'll grab the latest master, and give it a go.  For reference the inspect times with the 0.6.1 version running:
```
nukeeper inspect -v d -c patch -s https://internalnugetserver/nuget/
```
First (hits web server) inspect: 10s
Second (cached) inspect: 2m18s

In terms of solution/project sizes:
Found 12728 packages in use, 321 distinct, in 340 projects.

I'm not sure where I got 390 from, as it's not quite that many!  And they're from internal, and external sources.

**Comment by cg110** [comment]
Do you want a separate bug on the socket consumption (I realise my original description was unclear, in the case the cache is hit there is no socket used to talk to the web server)

In the first inspect there appears to be a https connection per package (which is probably not a friendly thing to do to the web servers)

The change for this has fixed the second inspect where there's cache locking problems, and the performance was appalling (I don't know why, but I assume it's something to do with parsing cache files)

I was wondering if PackageMetadataResource needs to be cached, but I can't tell if it's thread safe or not to do so.

**Comment by cg110** [comment]
Hmm, looks like the core nuget update has code to restrict it to running maxTasks (4) tasks at a time:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs#L670

Perhaps something similar in BulkPackageLookup.FindVersionUpdates would also work.  I'll see if I can throw something together.

**Comment by cg110** [comment]
Version using a task limit (sorry I don't have github setup locally to make a proper pull request):

All within BulkPackageLookup.cs, add a new const:
```c#
// Possibly tune this further, 10 stops the code hitting servers with 1 connection per package
// nuget internally looks to use 4, but this seemed quite a bit slower.
private const int maxNugetApiTasks = 10;
```

Then update the code to:
```c#
public async Task<IDictionary<string, PackageLookupResult>> FindVersionUpdates(
    IEnumerable<PackageIdentity> packages,
    NuGetSources sources,
    VersionChange allowedChange)
{
    var tasks = new List<Task<PackageLookupResult>>(maxNugetApiTasks);

    var latestOfEach = packages
        .GroupBy(pi => pi.Id.ToLowerInvariant())
        .Select(HighestVersion);

    var result = new Dictionary<string, PackageLookupResult>(StringComparer.OrdinalIgnoreCase);

    foreach (var latestPackage in latestOfEach)
    {
        if (tasks.Count >= maxNugetApiTasks)
        {
            ProcessLookupResult(await CompleteAndRemoveAnyTask(tasks), result);
        }

        var lookupTask = _packageLookup.FindVersionUpdate(latestPackage, sources, allowedChange);
        tasks.Add(lookupTask);
    }

    foreach (var lookupResult in await Task.WhenAll(tasks))
    {
        ProcessLookupResult(lookupResult, result);
    }

    return result;
}

private async Task<T> CompleteAndRemoveAnyTask<T>(List<Task<T>> tasks)
{
    var completeTask = await Task.WhenAny(tasks);
    tasks.Remove(completeTask);
    return await completeTask;
}
```

The code is now limited to 10 version check tasks, and so 10 nuget connections/ssl sockets per source.  Note that this does potentially mean that we'll run at the speed of the slowest nuget source, but I suspect that was always the case, and in fact this may mean far less tasks for .net to manage, and possibly even some memory savings to be had.

**Comment by AnthonySteele** [comment]
>  the speed of the slowest nuget source

That can be bad, to be honest. I often have internal source set up, then I take the laptop home and they're just not reachable, and time out.

**Comment by cg110** [comment]
I suspect right now with all 300 requests firing off at the same time, you probably get them all timeout about the same time.  This change could make that 300/10 * the timeout length :(  I guess more smarts would be needed to detect a source was not actually available.

**Comment by AnthonySteele** [comment]
Released today

**Comment by cg110** [comment]
Just to confirm the performance change with 0.6.2.  The first run is took ~8.6s, the second (cached) run is ~5.8s.

So much improved, still a spike in connections for the first uncached case, but that's expected.
