### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#412]
It should possible to run nukeeper in a docker container.
We should document a working setup

**Comment by skolima** [comment]
Previous notes: https://github.com/NuKeeperDotNet/NuKeeper/issues/305

**Comment by AnthonySteele** [comment]
Nukeeper doesn't run on some Linuxes because of https://github.com/NuKeeperDotNet/NuKeeper/issues/333 - perhaps we should revisit that?

**Comment by cookie1981** [comment]
So I think my initial problem with this was due to my lack of xp writing dockerfiles.
After a bit of googling I've had a bit more success; have created an image created, and it can now see NuKeeper installed in the global tools (previous attempts we suggesting that it had not been installed, even though dotnet tools list -g showed it was there.)

I'm getting 'Unhandled Exception: Octokit.AuthorizationException: Bad credentials' on the last attempt, but I think this is down to another root cause which I'm working on now (just waiting for updates to my machine)
Will post more asap.

**Comment by cookie1981** [comment]
ok, here is my docker file: 

```
FROM microsoft/dotnet:2.1-sdk

RUN dotnet tool install NuKeeper -g

ENV PATH="${PATH}:/root/.dotnet/tools"

CMD NuKeeper repo https://github.com/privaterepo accessToken --maxpr 10 --change Patch --exclude ^Microsoft.AspNetCore
```
run the following commands on the terminal: 

docker build . -t nukeeper
docker run nukeeper

Here is the output: 

> GitHub public email missing from profile, falling back to .gitconfig
> User fork created at git://github.com/cookie1981/privaterepo.git for cookie1981
> Git clone https://github.com/privaterepo to /tmp/NuKeeper/accessToken
> Failed on repo privaterepo TypeInitializationException : The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.

First 3 lines of output are always logged, even when this command works on my windows VM, so they look unrelated.

docker -v
Docker version 18.06.1-ce, build e68fc7a
macOS v10.13.3

The same command runs fine directly on my windows VM

**Comment by skolima** [comment]
Right. So, this either needs `FROM 2.1-sdk-bionic` (#305 ) or we'd need to update to a beta `LibGitSharp` (#333  ) and accept their nonstandard versioning convention ;-) ?

**Comment by AnthonySteele** [comment]
And speaking of `Libgit2sharp`: https://github.com/NuKeeperDotNet/NuKeeper/pull/413

**Comment by cookie1981** [comment]
@skolima access to the bionic base image seems to be restricted. Are you able to use this?
And does it work?

**Comment by skolima** [comment]
@cookie1981 Checked again now, on a clean box - it does work and the base image is public. Perhaps there's a typo somewhere?

**Comment by slang25** [comment]
Following on from the suggestions here, I tried with the following dockerfile against master:

```Dockerfile
FROM microsoft/dotnet:2.1-sdk as builder
COPY . /NuKeeper
WORKDIR /NuKeeper

RUN dotnet restore
RUN dotnet publish -c Release NuKeeper/NuKeeper.csproj -f netcoreapp2.1

FROM microsoft/dotnet:2.1-runtime

COPY --from=builder /NuKeeper/NuKeeper/bin/Release/netcoreapp2.1/publish/ /NuKeeper/

WORKDIR /NuKeeper

ENTRYPOINT ["dotnet", "/NuKeeper/NuKeeper.dll", "repo", "https://github.com/justeat/JustSaying", "--maxpr", "10", "--change", "Patch", "--exclude", "^Microsoft.AspNetCore", "-r", "ReportOnly"]
```

When I do `docker run` I pass the access token by env var with `-e` and it works great!

**Comment by AnthonySteele** [comment]
Good idea to mention the env var. In this kind of scenario, it might be better to keep the access token in the env var `NuKeeper_github_token`

**Comment by slang25** [comment]
The way I saw it is that dotnet global tools are about convenience of getting it on your path, so here we'd run the global install, and then run a command to fixup `PATH` so that we can run it once. So it wouldn't be as convenient as just calling `dotnet`.

There would be value if you wanted to run a shell in the container and run `nukeeper` multiple times though, so I'll give that a go and report back.

**Comment by cookie1981** [comment]
@slang25 in your second stage of your dockerfile, you are pulling from the runtime rather than the SDK, but when the commands execs, they will call commands that are only available via the SDK, so I don't think your dockerfile will work in all scenarios.

**Comment by slang25** [comment]
It does work, however if you need `dotnet install tool` then you need to go back to SDK.

The thing with dotnet install is that it's really wants to get the package from nuget.org, you can add feeds from the command line, but you will need to give it a custom config to remove nuget.org, I don't think this is the idiomatic approach.

**Comment by AnthonySteele** [comment]
Yes, Nukeeper as a global tool is hosted on nuget.org. The private feed option does work with the syntax `--add-source http://packages.mydomain.com/nuget/feed`  but is not necessary in this case.

**Comment by slang25** [comment]
Ah, I hadn't appreciated this is what you were after, I thought it was for using it from source for dev and build, as opposed to getting a release.

**Comment by cookie1981** [comment]
@AnthonySteele  @slang25 

here is the docker file that I am currently using while pulling latest from the repo.

```
FROM microsoft/dotnet:2.1-sdk as builder

COPY . /build
WORKDIR /build/nukeeper

RUN dotnet test NuKeeper.Tests/NuKeeper.Tests.csproj --filter "TestCategory!=WindowsOnly"
RUN dotnet test NuKeeper.Inspection.Tests/NuKeeper.Inspection.Tests.csproj --filter "TestCategory!=WindowsOnly"
RUN dotnet test NuKeeper.Update.Tests/NuKeeper.Update.Tests.csproj --filter "TestCategory!=WindowsOnly"
RUN dotnet test NuKeeper.Integration.Tests/NuKeeper.Integration.Tests.csproj --filter "TestCategory!=WindowsOnly"

RUN dotnet publish -c Release ./NuKeeper/NuKeeper.csproj -f netcoreapp2.1

FROM microsoft/dotnet:2.1-sdk

COPY --from=builder /build/nukeeper/NuKeeper/bin/Release/netcoreapp2.1/publish/ /NuKeeper/

WORKDIR /NuKeeper

ENTRYPOINT dotnet /NuKeeper/NuKeeper.dll [args]
```
I've omitted [args] just because what I'm actually using is quite verbose.

To address @AnthonySteele comments above "But getting the latest version of a global tool also gives you the code at a known good release checkpoint, rather than HEAD of the repo."
I actually have 2 pipelines in place, one to build and test the latest code in the repo, and one to use the artificats of the last successful build to actually spin up a container and apply the updates. The container is then destroyed.

I'd like to replace those individual `dotnet test` commands with a single 'dotnet test' at a global level, but that seems problematic at the moment.

**Comment by slang25** [comment]
I needed to change the paths slightly, also used runtime image. Works great 👍 
```dockerfile
FROM microsoft/dotnet:2.1-sdk as builder

COPY . /build
WORKDIR /build

RUN dotnet test NuKeeper.Tests/NuKeeper.Tests.csproj --filter "TestCategory!=WindowsOnly"
RUN dotnet test NuKeeper.Inspection.Tests/NuKeeper.Inspection.Tests.csproj --filter "TestCategory!=WindowsOnly"
RUN dotnet test NuKeeper.Update.Tests/NuKeeper.Update.Tests.csproj --filter "TestCategory!=WindowsOnly"
RUN dotnet test NuKeeper.Integration.Tests/NuKeeper.Integration.Tests.csproj --filter "TestCategory!=WindowsOnly"

RUN dotnet publish -c Release ./NuKeeper/NuKeeper.csproj -f netcoreapp2.1

FROM microsoft/dotnet:2.1-runtime

COPY --from=builder /build/NuKeeper/bin/Release/netcoreapp2.1/publish/ /NuKeeper/

WORKDIR /NuKeeper

ENTRYPOINT dotnet NuKeeper.dll repo https://github.com/justeat/JustSaying --maxpr 10 --change Patch --exclude ^Microsoft.AspNetCore -r ReportOnly
```

**Comment by spboyer** [comment]
Does not work when needing to create a PR. Error returned

```console
Updates failed InvalidOperationException : Failed to build signature, did not get valid git user identity from github token or from repo config
```

I believe coming from the Checkout method? https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper/Engine/Packages/PackageUpdater.cs#L60

**Comment by skolima** [comment]
The git client needs the git user data to come from somewhere. There used to be a reasonable error when it was missing, perhaps refactoring removed it... https://github.com/NuKeeperDotNet/NuKeeper/pull/219
Two options are: have a valid .gitconfig existing or have a public-visible (just for authenticated users) email address on the user.

**Comment by spboyer** [comment]
@skolima easy fix in the container.

```console
RUN git config --global user.email $GIT_USER_EMAIL
RUN git config --global user.name $GIT_USER_NAME
```

Can set `IF` as well to determine if the variables exists etc.

**Comment by AnthonySteele** [comment]
So the current state with version NuKeeper 0.9.0, as far as I know, is that NuKeeper in a docker container should work so long at that container is a supported Linux or Windows, with NETCore 2.1 installed.

No bug issue, but possibly some docs needed. Is that correct?

**Comment by AnthonySteele** [comment]
Docs ssue
