### ISSUE TITLE
Cannot install NuKeeper on Ubuntu 18.04

### ISSUE THREAD

**Issue by pgrm** [NuKeeperDotNet/NuKeeper#433]
We have a Ubuntu 18.04 based jenkins agent, which has dotnet installed and should be running nukeeper once a week. It used to work on Ubuntu 16.04 but not on 18.04 anymore.

`dotnet --version` gives me `2.1.402`

`dotnet tool install --global NuKeeper` gives me

> The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.

> Tool 'nukeeper' failed to install. Please contact the tool author for assistance. 

installing specific versions or older ones also didn't work.

on my windows laptop and red hat enterprise based workstation (both same .net core version) it works without any problems

However, installing `dotnet-sonarscanner` (with `dotnet tool install --global dotnet-sonarscanner`) also works on ubuntu 18.04

I've found a similar issue, where the suggest it might be due to camel case problems: https://github.com/dotnet/cli/issues/9974 - although they claim it is only a WSL problem, the jenkins agent is running on AWS in a native Ubuntu environment and has the same problem.

Any ideas how to fix it? Maybe you can adjust something on your side, so it also works on stricter systems?

Thank you!

**Comment by AnthonySteele** [comment]
Hm, we're still using SDK `2.1.400`, if that's relevant. We will update some time soon.

**Comment by pgrm** [comment]
Thx, but the SDK doesn't seem  to be the issue, as it works with the same
SDK on windows and RHEL.

**Comment by AnthonySteele** [comment]
So this and general  linux compatibility is an argument that the tool name should be all in lower case. That might break running things, though.

**Comment by AnthonySteele** [comment]
I had the same thing on  Amazon Linux today.  :( Would making the tool name all lower case fix this?

**Comment by pgrm** [comment]
frankly, I don't know - I think it has something to do with an update introduced in ubuntu 18.04 - I've set up a build agent to run ubuntu 16.04 just for NuKeeper and there it works with exactly the same .net core version, ... So I really don't know which part of ubuntu 18.04 screwed it over and if changing the name would help. Sorry.

**Comment by AnthonySteele** [comment]
I have tried a couple of new installs, and I am seeing the same thing on Linux on Windows 10 and Linux on AWS. Both are  Ubuntu 18.04 so you may be right about that.

**Comment by AnthonySteele** [comment]
I think that it is a caps issue. I confirmed by doing the following:

* Do my usual `dotnet build; dotnet pack` to produce `NuKeeper.0.8.1.nupkg` locally from the source.
* Copy the package file to `C:\temp\NuKeeper.0.8.1.nupkg`.
* Open Ubuntu 18 in WSL, run `dotnet tool install NuKeeper --global --add-source /mnt/c/temp/`
* observe the usual error when the tool package is found by not processed: `The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.`

Then:

* in `C:\Code\NuKeeper\NuKeeper\`, change `NuKeeper.csproj` to `nukeeper.csproj` - This affects the tool name as it is defaulted to the project name.
* Clear out build artefacts, repeat the `dotnet build; dotnet pack`  to produce `nukeeper.0.8.1.nupkg`.
* Clear the temp folder of `*.nupkg`
* Copy the new package file to `C:\temp\nukeeper.0.8.1.nupkg`.
* Open Ubuntu 18 in WSL, run `dotnet tool install nukeeper --global --add-source /mnt/c/temp/`
* Observe success message: `Tool 'nukeeper' (version '0.8.1') was successfully installed.`
* the command `nukeeper` can be run in ubuntu on WSL. But `NuKeeper` can not.

**Comment by KathleenDollard** [comment]
Adding @wli3 and @livarcocc

We need to improve the error message. 

I'm a wee tad uncertain about what else we need to do to help tool authors. Are there OS's that can't run mixed case executables, or are we grabbing something from the wrong place and resulting in a mismatch in case?

Can you share the contents of the DotnetToolSettings.xml file? It's created for you automatically when you use PackAsTool true? Can you also confirm the case of your dll? 

Thank you for helping us get to the bottom of this as it will certainly affect other tools as well.

**Comment by wli3** [comment]
I tried 

```Do my usual dotnet build; dotnet pack to produce NuKeeper.0.8.1.nupkg locally from the source.
Copy the package file to C:\temp\NuKeeper.0.8.1.nupkg.
Open Ubuntu 18 in WSL, run dotnet tool install NuKeeper --global --add-source /mnt/c/temp/
observe the usual error when the tool package is found by not processed: The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
```

but I cannot repro it. Is there a package on nuget that I can try?

![image](https://user-images.githubusercontent.com/6993335/46380623-dc94e500-c657-11e8-8eb4-f156ce99ffe3.png)

The second case is a problem. The command name in manifest is "NuKeeper". Since we completely rely on OS/shell to call the shim, it depends on OS's rule. So on Windows, `nukeeper` can be used and on unix only `NuKeeper`. And in that side nothing we can do since SDK is not involved at invoke time. Note, the following line is correct in the message `You can invoke the tool using the following command: NuKeeper`

(on local tools, the current decision is to ignore case)

**Comment by AnthonySteele** [comment]
Hi @wli3 , thanks for looking into this.
The package is here on nuget: https://www.nuget.org/packages/NuKeeper/
This worked for me on Ubuntu 16, but now does not on Ubuntu 18.

**Comment by AnthonySteele** [comment]
Hi, @KathleenDollard,  thanks for looking into this.

I have reverted to the first case with `NuKeeper.csproj`, and the dll is called `NuKeeper.dll` 

I build, and pack. Then using Nuget package explorer, I can open the package and find the file `tools\netcoreapp2.1\any\DotnetToolSettings.xml` containing 

```xml
<?xml version="1.0" encoding="utf-8"?>
<DotNetCliTool Version="1">
  <Commands>
    <Command Name="NuKeeper" EntryPoint="NuKeeper.dll" Runner="dotnet" />
  </Commands>
</DotNetCliTool>
```

This file is indeed created automatically, the csproj contains `<PackAsTool>true</PackAsTool>`

**Comment by AnthonySteele** [comment]
I have tried a third variation today, and I still  get the error:

* The project file is `NuKeeper.csproj` and the resulting dll is `NuKeeper.dll`.
* project file now also contains `<ToolCommandName>nukeeper</ToolCommandName>` i.e. force lower case in the tool name.
* `dotnet pack` produces `NuKeeper.0.8.1.nupkg` 
* Package explorer confirms that this package contains `tools\netcoreapp2.1\any\DotnetToolSettings.xml` containing the line ` <Command Name="nukeeper" EntryPoint="NuKeeper.dll" Runner="dotnet" />` note lower case name now.
* Copy this file to c:\temp
* Open Ubuntu 18.04 on WSL
* issue commands: `dotnet tool uninstall nukeeper --global` and `dotnet tool install nukeeper --global --add-source /mnt/c/temp/`
* error is as before: `The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'nukeeper' failed to install. Please contact the tool author for assistance.`

**Comment by KathleenDollard** [comment]
We are looking in to this and appreciate any more insight you get. To clarify, as long as you know, the problem only exists on WSL and Ubuntu 18.04. @wli3 may have more questions.

**Comment by AnthonySteele** [comment]
Thanks. @KathleenDollard That's not entirely correct. Yes I can reproduce the issue on WSL and Ubuntu 18.04, but both @pgrm and I have seen this issue on Ubuntu 18.04 Linux on a VM, without WSL involved.

**Comment by AnthonySteele** [comment]
today I did this on ubuntu: `dotnet tool install nukeeper -v d --global`

It produces a load of output, ending 

```
      Acquired lock for the installation of NuKeeper 0.8.1
         Installing NuKeeper 0.8.1.
         Completed installation of NuKeeper 0.8.1
         Scanning packages for runtime.json files...
         Restoring packages for .NETCoreApp,Version=v2.1/any...
         Resolving conflicts for .NETCoreApp,Version=v2.1/any...
         Skipping compatibility checks of the ridless graph for DotnetToolReference project type. This graph is not used.
         Checking compatibility of packages on .NETCoreApp,Version=v2.1 (any).
         Checking compatibility for restore 1.0.0 with .NETCoreApp,Version=v2.1 (any).
         Checking compatibility for NuKeeper 0.8.1 with .NETCoreApp,Version=v2.1 (any).
         All packages and projects are compatible with .NETCoreApp,Version=v2.1 (any).
         Committing restore...
         Writing lock file to disk. Path: /home/anthonysteele/.dotnet/tools/.store/.stage/31ej0kr0.ias/project.assets.json
         Restore completed in 6.38 sec for /tmp/4ycwf0ia.xvh/restore.csproj.

         NuGet Config files used:
             /home/anthonysteele/.nuget/NuGet/NuGet.Config

         Feeds used:
             https://api.nuget.org/v3/index.json
             /usr/share/dotnet/sdk/NuGetFallbackFolder

         Installed:
             1 package(s) to /tmp/4ycwf0ia.xvh/restore.csproj
       Done executing task "RestoreTask".
     1>Done building target "Restore" in project "restore.csproj".
     1>Done Building Project "/tmp/4ycwf0ia.xvh/restore.csproj" (Restore target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:07.50
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'nukeeper' failed to install. Please contact the tool author for assistance.
```

**Comment by wli3** [comment]
@AnthonySteele I get a repro on WSL ubuntu 18.04 but I cannot get a VM repro. Let me keep digging

**Comment by wli3** [comment]
I created https://github.com/dotnet/cli/issues/10101 on CLI repo

**Comment by AnthonySteele** [comment]
Here is my cloud VM repro:
Open AWS console
EC2 
Launch instance
".NET Core 2.1 with Ubuntu Server 18.04 - Version 1.0 - ami-34435ede"
t2.micro
create a key pair, save it in the right place with the right perms.

ssh in from my machine using WSL (  `ssh -i ~/.ssh/temp_key.pem ubuntu@ec2-some_serial_no.eu-west-1.compute.amazonaws.com`

```
dotnet --list-sdks
2.1.302 [/usr/share/dotnet/sdk]

dotnet tool install NuKeeper --global

The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'nukeeper' failed to install. Please contact the tool author for assistance.
```


Ok, lets try updating that:

```
sudo apt-get upgrade

--- several minutes of text  scrolls past

dotnet --list-sdks
2.1.403 [/usr/share/dotnet/sdk]
 dotnet tool install NuKeeper --global
 
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'nukeeper' failed to install. Please contact the tool author for assistance.
```

**Comment by AnthonySteele** [comment]
@wli3 is there any workaround in the short term?
All that I have come up with is changing the project name to `nukeeper.csproj` -  all lower case, which will chnage the dll name, the nuget package name and the tool command name to same lower case?

**Comment by wli3** [comment]
Thanks for the repro!

You can customize tool command name using the following in csproj <ToolCommandName>nukeeper</ToolCommandName>

and you can customize the package name using the following in csproj

<PackageId>nukeeper</PackageId>

**Comment by wli3** [comment]
[Update]

I believe the following is the problem, it should be InvariantCultureIgnoreCase
https://github.com/dotnet/cli/blob/d0881898575c61a672d1f643efb70956a020e281/src/dotnet/ToolPackage/ToolPackageInstance.cs#L215

Console.WriteLine(string.Compare("nukeeper", "NuKeeper", StringComparison.CurrentCultureIgnoreCase) == 0);

is false here

**Comment by AnthonySteele** [comment]
That's great, thanks for finding that. Can you give some idea of when this fix is likely to be shipped, as it impacts if / how I work around the issue in the meantime?

**Comment by AnthonySteele** [comment]
@wli3 

Today's workaround works, as is as follows - In `NuKeeper.csproj` add the lines:
```
    <PackageId>nukeeper</PackageId>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>nukeeper</ToolCommandName>
```

I verified that it works with the usual process as above to produce a package `nukeeper.0.8.2.nupkg` locally, and install  it onto WSL Ubuntu using ` dotnet tool install nukeeper -g --add-source /mnt/c/temp`

So I could do this change, but will the package with changed caps work with the existing feed at https://www.nuget.org/packages/NuKeeper/ ?

**Comment by wli3** [comment]
> Can you give some idea of when this fix is likely to be shipped

Sorry I don't know at this point. I am **trying** to get it in 2.1.4xx serving. Please following the issue on CLI to get the latest progress.

>  if / how I work around the issue in the meantime?

The impact is when people have culture set to en-US-posix(and other cultures that consider the 2 string at not the same). The install will return false. Your workaround should work. Please give me some time to confirm 2 name can co exist in the same feed. On client side it is https://github.com/NuGet/Home/issues/2522

**Comment by wli3** [comment]
confirmed, this workaround can work

**Comment by AnthonySteele** [comment]
Please try again with  [NuKeeper v 0.9.0](https://www.nuget.org/packages/NuKeeper/0.9.0).
We should now have `dotnet tool install nukeeper --global` (NB lower case)

**Comment by AnthonySteele** [comment]
[This AWS cloud repro](https://github.com/NuKeeperDotNet/NuKeeper/issues/433#issuecomment-427278729) now works fine with Ubunto 18.04 and [NuKeeper v 0.9.0](https://www.nuget.org/packages/NuKeeper/0.9.0).

Commandline is  `dotnet tool install nukeeper --global` (NB lower case)

**Comment by pgrm** [comment]
@AnthonySteele it works, thank you

**Comment by AnthonySteele** [comment]
FYi, as per #475, I also had to do `sudo apt-get install libcurl3` before it worked on ubuntu 18.
