### ISSUE TITLE
Regression: command line fork mode ignored in 8.0.0

### ISSUE THREAD

**Issue by skolima** [NuKeeperDotNet/NuKeeper#453]
Command line:
`NuKeeper org MyOrg %GitHubAccessToken% --maxpr=50 --maxrepo=500 --source=https://api.nuget.org/v3/index.json --source=%internal-feed% -v:d --fork=SingleRepositoryOnly --label=nukeeper --label=review-requested`

0.7.2 results in:
`FindPushFork. Fork Mode is SingleRepositoryOnly`
0.8.0 results in:
`FindPushFork. Fork Mode is PreferFork`

**Comment by pgrm** [comment]
having same issu

**Comment by AnthonySteele** [comment]
Does it do the same with spaces not equal signs, e.g. `--fork SingleRepositoryOnly` ?

**Comment by AnthonySteele** [comment]
Cause seems to be that the commandline is being read just fine, but the `ForkFinder` is being created before that.

**Comment by AnthonySteele** [comment]
Will be fixed in `0.8.1`

**Comment by AnthonySteele** [comment]
Version `0.8.1` should be visible shortly.
