### ISSUE TITLE
support for nanoFramework project extension

### ISSUE THREAD

**Issue by josesimoes** [NuKeeperDotNet/NuKeeper#456]
Hi,

I'm in the [nanoFramework](https://github.com/nanoframework/) project team.
Because we have a lot of libraries that depend on each other, we would like to automate the CI.
We have our own CPS project system, based on C# (csproj) but using our own extension: nfproj. Everything inside (as far as Nuget is concerned) works exactly as if it was a typical csproj.
My question is: would you consider to add support for nfproj in NuKeeper? It seems perfect for what we are trying to accomplish. 😃 
We would submit a PR with this, of course.

**Comment by AnthonySteele** [comment]
Hi. Yes, we can do this.
We found that with `.fsproj` and `.vbproj`, the project file contents work the same. Another file extension for the same data shouldn't be a big thing.

**Comment by josesimoes** [comment]
Awesome! 👍  I'm on it!

**Comment by josesimoes** [comment]
@AnthonySteele just realized that for nuget to be able to fully update the nfproj it requires a "hack" to keep the nuget exe happy: the project file has to be renamed from .nfproj to .csproj and then back to .nfproj.

Can I submit a PR with this fix?
