### ISSUE TITLE
Update/sync dependencies in nuspec files

### ISSUE THREAD

**Issue by shatl** [NuKeeperDotNet/NuKeeper#485]
Would be great to have an ability to update dependencies in .nuspec files based on csproj package references.

E.g. if Package1 was updated to version 1.2.0 and there is a .nuspec file with the same name as .csproj exists update `<dependency id="Package1" version="1.0.0" /> to version `1.2.0` as well

Thanks

**Comment by skolima** [comment]
This was done in https://github.com/NuKeeperDotNet/NuKeeper/pull/264 , is there anything else missing?

**Comment by shatl** [comment]
Sorry, Looks like I missed that update.
