### ISSUE TITLE
Bitbucket integration

### ISSUE THREAD

**Issue by rbev** [NuKeeperDotNet/NuKeeper#488]
Related to  #336, #327 

It would be great to have support for raising pull requests in Atlassian Bitbucket as well.

**Comment by rbev** [comment]
Agreed.
Since i currently use on-prem bitbucket I would be happy to put together a pull request to add support for this (assuming i can find the time)

I'll try to have a look once i see the related pending pull requests get completed.

**Comment by Jens-H-Eriksen** [comment]
Hi Rhys,
Did you have time to look into solution for this issue. We are using Bitbucket as well and would really like the feature.

**Comment by MarcBruins** [comment]
AzureDevops is merged in #513 not everything is implemented but yet but it should give an idea!

**Comment by MarcBruins** [comment]
Please see #522 for bitbucket integration. I've been able to succesfully update nuget packages on my bitbucket repo using NuKeeper

**Comment by MarcBruins** [comment]
Think this issue can be closed

**Comment by joaoportela** [comment]
Does this work with self-hosted bitbucket installations?

**Comment by Jens-H-Eriksen** [comment]
Yes, It works with a self-hosted bitbucket... What parameters are you using when calling NuKeeper ?

**Comment by joaoportela** [comment]
```
$ nukeeper repo https://USERNAME@abc.def.xyz/projects/PROJ/repos/xyz-repo/ MYPASSWORD
Unable to work out which platform to use https://code.abyssal.eu/projects/CLOUD/repos/abyssal-cloud/ could not be matched
```

I think this may be because of the issue I just reported: #614

**Comment by joaoportela** [comment]
> But anyway: The problem is your URL that should contain the word "bitbucket." Otherwise NuKeeper do not know what platform to use.

It definitely does not contain the word bitbucket. I'll try and work around that, thanks.
