### ISSUE TITLE
CLI command not found

### ISSUE THREAD

**Issue by TraGicCode** [NuKeeperDotNet/NuKeeper#498]
I performed a global install but the CLI tool is like it's not being found for some reason.  This is a known bug already?

```
> dotnet tool list -g

Package Id           Version      Commands
-------------------------------------------------
dotnet-outdated      2.1.0        dotnet-outdated
nukeeper             0.9.1        nukeeper

> dotnet nukeeper

No executable found matching command "dotnet-nukeeper"

> nukeeper
zsh: command not found: nukeeper
```

**Comment by skolima** [comment]
This should not cause issues since 0.9.0 :-( https://github.com/NuKeeperDotNet/NuKeeper/issues/433#issuecomment-429642920

**Comment by AnthonySteele** [comment]
`nukeeper` should be invoked as `nukeeper`, all lower case (not `dotnet nukeeper`).
If this does not work, it might not be correctly on the path. You should be able to call it as ` ~/.dotnet/tools/nukeeper`

**Comment by TraGicCode** [comment]
Hey @AnthonySteele ,

Running ~/.dotnet/tools/nukeeper worked.  Does this simply mean i need to perform a reboot?  I figured reloading zsh would fix this.

**Comment by AnthonySteele** [comment]
Unfortunately I'm not an expect on how zsh handles path. You might need to add ` ~/.dotnet/tools/` to the path for >NET core tools in general?

**Comment by slang25** [comment]
`~/.dotnet/tools/` should be on your path, when you install the dotnet SDK it adds it for bash, but not sure about zsh, there is an issue here:
https://github.com/dotnet/cli/issues/9321

You can follow this instruction to fix it manually:
https://github.com/dotnet/cli/issues/9321#issuecomment-406915716
