### ISSUE TITLE
Question: Is it possible to use the new Azure Devops support with TFS?

### ISSUE THREAD

**Issue by EP01** [NuKeeperDotNet/NuKeeper#532]
I'm running TFS 2018 Update 3.1 (the latest version). I've tried running `nukeeper repo https://mytfsrepo` but it gives an `Unable to work out which platform to use` error. Can I tell it to use the Azure Devops platform?

**Comment by MarcBruins** [comment]
That is currently not possible. i guess TFS has a local API which we could target and that could make it work but then we need to know somehow (extra param?) what that API is.

**Comment by shep1987** [comment]
I have a version of TFS at work i can test this on, will try and find some time this week. We are targeting version 4.1 of the API so only 2018 Update 2 and above will be supported.

**Comment by EP01** [comment]
Thanks guys! Hopefully the API is not too far removed from Azure Devops, and a parameter can be added to specify the platform. Please let me know if there's anything I can help with regarding the implementation of this.
