### ISSUE TITLE
Question: What are the details of the package selection process (filtering)?

### ISSUE THREAD

**Issue by timmkrause** [NuKeeperDotNet/NuKeeper#544]
The first two runs show `Selection of package updates: 4 candidates, filtered to 3` what I do not really understand atm.

1. First run was the `repo` command without additional parameters and the following packages have been selected:

- `Swashbuckle.AspNetCore`
- `Swashbuckle.AspNetCore.Annotations`
- `FluentAssertions`

Log output:

```
Found 4 package updates
Microsoft.NET.Sdk.Functions to 1.0.24 from 1.0.23 in 1 place since 10 days ago.
FluentAssertions to 5.5.1 from 5.4.2 in 5 places since 2 days ago.
Swashbuckle.AspNetCore to 4.0.1 from 3.0.0 in 1 place since 11 days ago.
Swashbuckle.AspNetCore.Annotations to 4.0.1 from 3.0.0 in 1 place since 11 days ago.
Selection of package updates: 4 candidates, filtered to 3
Selected package update of Swashbuckle.AspNetCore to 4.0.1
Selected package update of Swashbuckle.AspNetCore.Annotations to 4.0.1
Selected package update of Microsoft.NET.Sdk.Functions to 1.0.24
Updating 3 packages
'Swashbuckle.AspNetCore' from 3.0.0 to 4.0.1 in 1 projects
'Swashbuckle.AspNetCore.Annotations' from 3.0.0 to 4.0.1 in 1 projects
'Microsoft.NET.Sdk.Functions' from 1.0.23 to 1.0.24 in 1 projects
Done 3 updates
```

2. Then I tried the `repo` command with `--consolidate` and the following packages have been selected:

- `Swashbuckle.AspNetCore`
- `Swashbuckle.AspNetCore.Annotations`
- `Microsoft.NET.Sdk.Functions`

3. If I run it with `inspect {localRepoPath} -v d` all 4 packages are included, what I actually would have expected.

Is this a bug or a feature? :) If it is a feature, what are the details behind the filtering logic?

**Comment by MarcBruins** [comment]
By default nukeeper will make a PR for the first 3 packages. It's just first come first serve. If you look at the options you will see the default is 3 for the P parameter: https://github.com/NuKeeperDotNet/NuKeeper/wiki/Configuration#options

**Comment by AnthonySteele** [comment]
There is sorting so that more impactful package updqtes come first (note that `Swashbuckle.AspNetCore` is in more places and the update has been around for longer than `FluentAssertions`.

The default count is the top 3, you can change that with `-p` / `--maxpr`

**Comment by timmkrause** [comment]
Ah, great!

The reason why I did not look into `--maxpr` was that my assumption was (because of its name) that NuKeeper scans the active pull requests created by it and does not create further PRs when the limit is reached. It was not clear to me that it controls the maximum number of package updates per pull request when in `--consolidate` mode.

Thanks for the insights, makes totally sense.

**Comment by timmkrause** [comment]
> Being aware of that this would be breaking change: Do you think it would make sense renaming it to something like `--maxpkgs` or something? Just a thought.
> 
> Please close the issue on your behalf.
> 
> Addition: From the configuration document (regarding `maxpr`) I would also understand a different behavior than controlling the maximum number of updates. Literally speaking `maxupdate` would have been the term which would make the most sense to me but this is reserved to the `update` command.

**Comment by MarcBruins** [comment]
Is there anywhere in writing how the filtering works? Would be nice to know(i realize now that i've seen in the code)

**Comment by AnthonySteele** [comment]
Sorting and filtering needs more docs, agreed.
And the `maxpr` option is increasingly  misnamed.

**Comment by phatcher** [comment]
The one that threw me initially is the exclusion for packages < 7 days old. I was thinking we might want to make the inclusion/exclusion log better to make the reasoning more apparent.

**Comment by AnthonySteele** [comment]
Moredetails given by #548
