### ISSUE TITLE
Self-hosted Bitbucket integration 

### ISSUE THREAD

**Issue by Jens-H-Eriksen** [NuKeeperDotNet/NuKeeper#547]
The self-hosted version of BitBucket does not include the version 2 of the API. It would be nice to have a version of NuKeeper that integrates to the Selfhosted version of BitBucket.

**Comment by MarcBruins** [comment]
This would be nice indeed. If anyone wants to work on this feel free, if you need guidance or help to get started feel free to chat on gitter: https://gitter.im/NuKeeperDotNet/Lobby
