### ISSUE TITLE
Setup a CI/CD enviroment

### ISSUE THREAD

**Issue by MarcBruins** [NuKeeperDotNet/NuKeeper#565]
We should advance our own CI/CD enviroment to make it easier to publish releases and keep code quality high. We should also hook in Docker and the ADO extension to this process.

For the continuous intergration enviroment:

- [x] Run unit-tests on different OSes
- [ ] Setup test repositories for all the platforms.
- [ ] Run intergration tests against the test repositories and automatically check the results.
- [ ] Is this enough?

For the continuous deployment, i imagine i would be based on a git tag with the version in it.

- [x] Automatically create a new release on and publish it on nuget
- [ ] Automatically update ADO extension
- [ ] Automatically update the Docker container(this can be done through docker CD which has Github Intergration)
- [ ] Create nightly build and publish on MyGet or similar

**Comment by AnthonySteele** [comment]
Agreed.

There is the [Travis CI](https://travis-ci.org/NuKeeperDotNet/NuKeeper/) that runs unit tests on Linux.
It's going to be important to do a lot more. Stating with running unit tests on multiple OSs, then doing outside-in tests with test repos.

Then a release/continuous deployment process.

**Comment by zubivan** [comment]
Might be relevant for this issue. I configured Windows and Linux nodes on Azure DevOps with this PR https://github.com/NuKeeperDotNet/NuKeeper/pull/829.
