### ISSUE TITLE
CLI option to allow updating prerelease packages to only stable packages

### ISSUE THREAD

**Issue by cswendrowski** [NuKeeperDotNet/NuKeeper#583]
First off, love this library!

Related to https://github.com/NuKeeperDotNet/NuKeeper/issues/175, my team uses prerelease builds of Nuget packages to continue doing work while the Nuget package PR is being reviewed. Once the package PR has been merged, we would like the option to update our existing branches to that stable release without considering upgrading to a newer Prerelease of that package via a parameter such as `--allowPrereleases false`

This is purely a convenience request since we can always manually update our local branches to the non-beta version in the few cases where a newer prerelease has been pushed out.

**Comment by AnthonySteele** [comment]
Hello, thanks for the feedback!

This is doable. We have discussed adding this option  before, but have not had a real reason to do so before now.
FYI, I was considering an enum with three modes: `AllowPrePrelease.Always`, `AllowPrePrelease.Never`, `AllowPrePrelease.FromPreRelease` where "Allow prerelease from prerelease" is the current behaviour and would stay as default. What you are describing is `Never allow prerelease`.

**Comment by cswendrowski** [comment]
I can take a stab at implementing this. It looks like most of the work is there and I just need to hook up a CLI parameter similar to https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper/Commands/CommandBase.cs#L23, correct?

**Comment by AnthonySteele** [comment]
That's correct, yes

**Comment by AnthonySteele** [comment]
If you have any questions along the way, try chat here: https://gitter.im/NuKeeperDotNet/Lobby
