### ISSUE TITLE
Needs a suitable open-source licence

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#59]
Which one?

**Comment by AnthonySteele** [comment]
The JE repos are licenced under -[the Apache2 licence](https://www.apache.org/licenses/LICENSE-2.0). Is this OK?

**Comment by slang25** [comment]
Is this a JE thing? If so Apache2 is going to be far less friction.

**Comment by AnthonySteele** [comment]
We did use JE hackathon time to get it started, in the hope that JE (and others) would benefit from NuKeeper. So ... maybe?

**Comment by AnthonySteele** [comment]
Apache 2!
