### ISSUE TITLE
Argument: "Platform"

### ISSUE THREAD

**Issue by Jens-H-Eriksen** [NuKeeperDotNet/NuKeeper#590]
As the number of platforms Nukeeper are supporting, are growing, I think It would be a good idea to add an argument, that tells Nukeeper which platform it should use instead of using the logic in the implementations of the CanRead method in ISettingsReader:

`nukeeper <platform> <command> command-arguments options`

**Comment by AnthonySteele** [comment]
I would put it in as an optional argument e.g. `--platform github` for cases where the inference fails.

**Comment by MarcBruins** [comment]
Optional argument sounds a good way forward. I actually like that NuKeeper figures out what platform you are using.

**Comment by MarcBruins** [comment]
Think we should still document this @AnthonySteele?

**Comment by AnthonySteele** [comment]
It should be documented now

**Comment by ElanHasson** [comment]
I'm trying to use the new `platform` argument from the command line and it doesn't appear to work.

On inspection of the command, it doesn't seem to care about it..

https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper/Commands/RepositoryCommand.cs#L49

**Comment by ElanHasson** [comment]
I've found the issue and will be sending a PR.
