### ISSUE TITLE
Bug when using --source

### ISSUE THREAD

**Issue by Jens-H-Eriksen** [NuKeeperDotNet/NuKeeper#591]
When using the option `--source` NuKeeper is failing, as it cannot restore packages that dos'nt exist in this Nuget source.

**Comment by AnthonySteele** [comment]
If you can, just rely on your `nuget.config` file.
if you use `--source` once or more, then this overrides the data in `nuget.config`.
if you have multiple sources that all need to be present, then specify `--source` more than once.

**Comment by Jens-H-Eriksen** [comment]
The Issue is that we want's to filter on source, as we want's to update all our own Nugetpackages when they have --age 0
public package updates should follow another schema

**Comment by sharpSteff** [comment]
stumpled over this as well.

It crashes on "Unable to locate the packages folder. Verify all the packages are restored befure running 'nuget.exe update'"

As working directory for the external process, the project folder is selected.
However when executing nuget restore with the solution folder as working folder, than everything works fine

**Comment by sharpSteff** [comment]
never mind...

specifying 
```
  <config>
	<add key="repositoryPath" value=".\packages" />
  </config> 

```

solved this issue for me
