### ISSUE TITLE
Option --report 

### ISSUE THREAD

**Issue by Jens-H-Eriksen** [NuKeeperDotNet/NuKeeper#592]
It seems like the option `--report` is not supported. Maybe it's a "bug" in the Wiki ?!

**Comment by AnthonySteele** [comment]
Not any more, that `report ` option should not be in the wiki any more. It has been replaced with the more flexible `outputformat` and `outputdestination` options. 

If you set `outputdestination` to `file` and `outputformat` to `csv` then it's equivalent.

**Comment by Jens-H-Eriksen** [comment]
Okay.. thx

**Comment by AnthonySteele** [comment]
I have removed that from the "Configuration" page.

thanks, well spotted.
