### ISSUE TITLE
Nukeeper inspect, order alphabetic

### ISSUE THREAD

**Issue by phatcher** [NuKeeperDotNet/NuKeeper#609]
Would be nice to order the output from inspect alphabetically, sometimes I can't use the automated update due to dependency issues but putting them all together I can work out how to apply the changes manually.

**Comment by MarcBruins** [comment]
Can you work on this @phatcher?

**Comment by phatcher** [comment]
@MarcBruins Yes, bit busy with work but I should be able to have a look at it next week

**Comment by BlackstarSolar** [comment]
While not desirable it's possible to have multiple versions of the same package in a single solution.  Can I suggest this is extended to be ordered alphabetically then by version?

**Comment by shep1987** [comment]
Had a quick play with this. branch here:

https://github.com/shep1987/NuKeeper/commit/4ff2cf0362408da8a2cbb520019a66c0f354aaf1

@AnthonySteele Can you provide some context into `PrioritySort` I wouldn't want to remove it if people are using it! From my point of view i didn't understand the order until i looked into this code.

**Comment by AnthonySteele** [comment]
`PrioritySort` is a heuristic (i.e. informal algorithm) to decide which package it is best to update first. This comes into play heavily when there are e.g. 50 potential updates, but a limit of will be applied. Which 3? You want the most impactful / important  / obvious ones, but the rules to determine that are a bit of a guess.

There are rules such as 

* If there is more than one current version in use, do that first - i.e prefer to consolidate. 
* Prefer to a package used in 2 places over a package used in 1 place
* Prioritise changes that have been around for longer (`ScoreAge`)
* Prioritise  changes that go from prerelease to release versions (get out of beta)


etc.  `PrioritySort` can  be modified, but it serves a purpiose. If you want to sort all potential updates alphabetically for display, do that to output just before displaying?
