### ISSUE TITLE
InvalidSpecificationException : malformed URL setting up Azure DevOps repo.

### ISSUE THREAD

**Issue by MaxMommersteeg** [NuKeeperDotNet/NuKeeper#613]
Getting this exception on following command:
`nukeeper repo https://myname.visualstudio.com/Aurora%20Borealis/_git/AuroraBorealis [TOKEN]`

>Failed on repo AuroraBorealis InvalidSpecificationException : malformed URL 'https://myname.visualstudio.com/Aurora Borealis/_git/AuroraBorealis/'

Same when using the new Azure DevOps-styled url:
`nukeeper repo https://MyName@dev.azure.com/MyName/Aurora%20Borealis/_git/AuroraBorealis [TOKEN]`

I am using a Personal Access Token that has rights for reading and writing code.

Sorted out what is causing the issue. The space between `Aurora Borealis` is causing it.

I encoded the URI to turn spaces into `%20` and it gets accepted correctly, however it fails when cloning the repository since it then tries to clone using following command:
`Git clone https://myname.visualstudio.com/Aurora Borealis/_git/AuroraBorealis/`

While following works:
`Git clone https://myname.visualstudio.com/Aurora%20Borealis/_git/AuroraBorealis/`

**Comment by shep1987** [comment]
Hi Max,

Thanks for the report, this is a case i didn't think about! I'm a bit snowed under with work at the moment so not sure when I will get to look at this.

If you fancy submitting a PR I think the issue will be in the `AzureDevOpsSettingsReader` We must be stripping the encoding either here or when we parse the URL.

**Comment by jmiddour** [comment]
I actually ran into the same issue!  I was in the process of logging an issue and submitting a PR, but Max beat me to it.

I will submit a PR.

**Comment by Rolorob** [comment]
Awesome! Thanks ❤️
