### ISSUE TITLE
Can't install the latest version

### ISSUE THREAD

**Issue by joaoportela** [NuKeeperDotNet/NuKeeper#614]
When I install (or update) nukeeper, it installs the wrong version.

When I do:

```
$ dotnet tool install -g nukeeper
You can invoke the tool using the following command: nukeeper
Tool 'nukeeper' (version '0.11.0') was successfully installed.
```

I should get `0.11.0`, but it seems that I'm actually getting version `0.10.2`:

```
$ nukeeper --version
Automagically update NuGet packages in .NET projects.
0.10.2
```

**Comment by MarcBruins** [comment]
This is probably version 0.11.0 but we changed the CD environment and we didn't do anything with the old value. Which apparently we should update as well.

**Comment by AnthonySteele** [comment]
Hi.


The version number in that assembly metadata is currently incorrect due to build process changes. We have already noticed this, and hope to have this correct at the next release. 

`dotnet tool list -g` will show the correct installed version.
