### ISSUE TITLE
Submodules support

### ISSUE THREAD

**Issue by joaoportela** [NuKeeperDotNet/NuKeeper#616]
I don't think NuKeeper is checking out submodules.

When running `nukeeper repo` command in a (bitbucket) project with sub-modules I get the following error:

Skipping project "/tmp/NuKeeper/434fe9fdf9ef4501a9797e1c61f2225d/folder/submodule/path/project.csproj" because it was not found.

Is this true? Am I doing something wrong?

**Comment by AnthonySteele** [comment]
No, we are not yet supporting submodules

**Comment by joaoportela** [comment]
OK. How can I help?

**Comment by MarcBruins** [comment]
Shouldn't it be the resposiblity of the `submodule` to update itself and not of the one using the submodule?

**Comment by joaoportela** [comment]
@MarcBruins Yes, but as it is right now the "main" project won't compile and nukeeper won't work. :(

**Comment by MarcBruins** [comment]
Ah ok, this seem unrelated to NuKeeper but more to do with your project. I'll close this issue because i don't think we ever want to support submodules(i think it should skip it which it does).

**Comment by joaoportela** [comment]
@MarcBruins I understand that NuKeeper shouldn't be responsible for updating the submodules.

But as it is right now it just doesn't work with projects that have submodules.

Not updating packages in submodules makes perfect sense like you said before, but the whole process failing just because you have submodules... Not so much.

Can't we change NuKeeper to checkout the submodules but not update them?
