### ISSUE TITLE
Question: Azure DevOps Extension

### ISSUE THREAD

**Issue by timmkrause** [NuKeeperDotNet/NuKeeper#618]
https://marketplace.visualstudio.com/items?itemName=nukeeper.nukeeper

If I install and use the extension, how do I know which version of NuKeeper is being used?
My current understanding is that these extensions do not need to be "updated" (when installed) in any manner.

So is the assumption correct that a version of this extension package comes with a specified/packaged version of NuKeeper and (once installed) if new versions of the extension are pushed to the marketplace (containing an updated version of NuKeeper) I am automatically using these new versions?

**Comment by MarcBruins** [comment]
Unfortunately this is still a manual process. So everytime there is a new version of NuKeeper we have to update the DevOps extension as well and include that version. This is definitely something we need to improve and if we can, automate. Right now i believe the extension uses version 0.10.2. 

I've tried using the `dotnet tool install` command but that didn't work for the Task back then. I'll have a look at this next week in how to automate it and also display same version information in the extension. Is there something you are missing in this version?

**Comment by MaxMommersteeg** [comment]
>I've tried using the `dotnet tool install` command but that didn't work for the Task back then.

So a few days I wanted to integrate NuKeeper in my Azure DevOps Build pipeline and have it run daily. I managed to install NuKeeper but stumbled upon following issue: https://github.com/NuKeeperDotNet/NuKeeper/issues/613

I did not even know about an Azure DevOps extension at that time. Installing with `dotnet tool install` could potentially select the highest minor version right? That would atleast automate it somewhat.

**Comment by timmkrause** [comment]
I was already using it via `dotnet tool install` but for me it would be somewhat easier to use the extension.
I was just curious about the update handling of the extension.

Definitely appreciate the idea of displaying the same version information in the extension.

And @MarcBruins: Nope, I am not missing something specific, so no stress on that.

I just wanted to clarify which version is inside the extension and that I receive the "latest version" of the extension when you perform updates on it which is obviously the case.

Thanks!

**Comment by MarcBruins** [comment]
What i was referring too, is make the **extension** use the `dotnet tool install` to make sure that the extension is up to date. Now it just packages up the DLL as you can here: [extension repo](https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension)

**Comment by MaxMommersteeg** [comment]
Indeed, that would be a better solution imho.

**Comment by timmkrause** [comment]
@MarcBruins Just realized that the version within the extension package is actually pretty old:

```
2018-12-20T07:57:42.9146973Z ##[section]Starting: NuKeeper
2018-12-20T07:57:42.9735452Z ==============================================================================
2018-12-20T07:57:42.9736111Z Task         : NuKeeper
2018-12-20T07:57:42.9736633Z Description  : Automagically update nuget packages in .NET projects
2018-12-20T07:57:42.9737121Z Version      : 0.1.42
2018-12-20T07:57:42.9737583Z Author       : NuKeeper
2018-12-20T07:57:42.9738002Z Help         : 
2018-12-20T07:57:42.9738486Z ==============================================================================
```

**Comment by MarcBruins** [comment]
That is the Task version not the NuKeeper version ;)

**Comment by timmkrause** [comment]
Ah, sorry. 2 coffees are not enough in the morning... ;)
