### ISSUE TITLE
Local branch already exists.

### ISSUE THREAD

**Issue by MaxMommersteeg** [NuKeeperDotNet/NuKeeper#619]
Something went wrong in my build pipeline (not sure what) and it left an old branch containing a package update. Retrying to update the package will result in following error:
>2018-12-19T19:02:46.4861358Z Updating'Microsoft.TestPlatform.TestHost' from 15.7.2 to 15.9.0 in 1 projects
>2018-12-19T19:02:46.4867575Z Git checkout 'master'
>2018-12-19T19:02:46.5653124Z Using branch name: 'nukeeper-update-Microsoft.TestPlatform.TestHost-to-15.9.0'
>2018-12-19T19:02:46.5729105Z Git checkout new branch 'nukeeper-update-Microsoft.TestPlatform.TestHost-to-15.9.0'
>2018-12-19T19:02:46.5867894Z Updates failed NameConflictException : failed to write reference 'refs/heads/nukeeper-update-Microsoft.TestPlatform.TestHost-to-15.9.0': a reference with that name already exists.
>2018-12-19T19:02:46.6037597Z    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
>2018-12-19T19:02:46.6038246Z    at LibGit2Sharp.Core.Proxy.git_branch_create_from_annotated(RepositoryHandle repo, String branch_name, String targetIdentifier, Boolean force)
>2018-12-19T19:02:46.6038749Z    at LibGit2Sharp.BranchCollection.Add(String name, String committish, Boolean allowOverwrite)
>2018-12-19T19:02:46.6039096Z    at NuKeeper.Git.LibGit2SharpDriver.CheckoutNewBranch(String branchName) in C:\Users\marc\Documents\repos\NuKeeper\NuKeeper.Git\LibGit2SharpDriver.cs:line 90
>2018-12-19T19:02:46.6040032Z    at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in C:\Users\marc\Documents\repos\NuKeeper\NuKeeper\Engine\Packages\PackageUpdater.cs:line 75
>2018-12-19T19:02:46.6040344Z    at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 updates, NuGetSources sources, SettingsContainer settings) in C:\Users\marc\Documents\repos\NuKeeper\NuKeeper\Engine\Packages\PackageUpdater.cs:line 46
>2018-12-19T19:02:46.6040524Z Attempted 1 updates and did 0
>2018-12-19T19:02:46.6048172Z Done at 2018-12-19T19:02:46Z

So NuKeeper is trying to create a new local branch with the same name, that already exists, which results in above error.

What should be the expected behaviour here?
- Leave it like this, is the error justified (the ADO account will never be able to delete its local branch (thus put up a PR for updating the package))
- Should it merge the update in existing local branch and open up an PR after?
- Should it create a branch with a different name (could result in multiple PR's with same changes)
- Other?

Nit. I am seeing:
>C:\Users\marc\Documents\repos\NuKeeper\NuKeeper.Git\LibGit2SharpDriver.cs

In the error log which seems a bit strange to me. But that is a whole other issue imho.

**Comment by MarcBruins** [comment]
Is this in the azuredevops extension?

**Comment by MaxMommersteeg** [comment]
Yes, you are right. Maybe this issue shouldn't have been raised here, but at the other repository.

**Comment by MarcBruins** [comment]
It's fine here. I actually had the same issue in #567 but that worked again after a while.. We need to investigate this. What if you run the commands locally on the same repository?

**Comment by MaxMommersteeg** [comment]
I will try to reproduce the issue later this day.

**Comment by MaxMommersteeg** [comment]
So I was going through the steps of reproducing the issue but was hold back because of recent closed issue: https://github.com/NuKeeperDotNet/NuKeeper/issues/613 since a new update of NuKeeper has not been released yet.

My steps are currently as follows:
1. Clone repository
2. `git checkout master`
3. `git checkout -b nukeeper-update-Microsoft.TestPlatform.TestHost-to-15.9.0` (or another branch name that NuKeeper will come up with.)
4. `git checkout master`
5. `nukeeper repo [REPO_URL] [TOKEN] -v detailed -p 30 -c Minor -i "Microsoft.TestPlatform.TestHost" -co`

I could try to reproduce the issue with a another repo but am not able to do this today.

**Comment by MaxMommersteeg** [comment]
I failed to reproduce the issue by following above steps. It did not mind having a branch that already existed. It actually used that branch to make changes and opened up a pr after.

**Comment by MarcBruins** [comment]
Ok, so the issue is something else and it's only the case for AzureDevops as far i know.

**Comment by OneCyrus** [comment]
may be it's just the local branch which is not removed. probably needs a ```git fetch -p``` to prune the branch

**Comment by MarcBruins** [comment]
The local branch shouldn't exist because the build agent should be clean everytime it starts. We can try it out by just adding a simple script task before nukeeper that does the `git fetch -p` but i don't think it will help

**Comment by MaxMommersteeg** [comment]
I no longer experience this issue. I will close it for now.
