### ISSUE TITLE
Travis builds twice for PRs

### ISSUE THREAD

**Issue by cohen990** [NuKeeperDotNet/NuKeeper#62]
https://github.com/NuKeeperDotNet/NuKeeper/pull/61

Look at the detail and you'll see two travis builds - one /push and one /pr

Need to go into the travis build settings and modify it so that it will only build a PR or only build a branch push

**Comment by AnthonySteele** [comment]
I guess we should turn off the "Build branch updates" one.

**Comment by AnthonySteele** [comment]
There's only 1 build when you open a PR, looks like the 2* is on a PR update (Plus branch update).

**Comment by AnthonySteele** [comment]
And when I'm at home I can turn it off.
