### ISSUE TITLE
Pull and merge master into branch containing update.

### ISSUE THREAD

**Issue by MaxMommersteeg** [NuKeeperDotNet/NuKeeper#620]
I have setup and tested the Azure DevOps extension for a few days now. I run a build containing a NuKeeper task every night.

This morning I opened up the list of active pull requests and saw one updated package. That had a merge conflict with master. I checked out the nukeeper branch but could not locate any merge conflicts in that branch. The master branch that was branched off for creating the nukeeper branch was not the latest version of master.

Currently the steps are as follows for nukeeper (correct me if wrong):
1. `git checkout master` (default branch)
2. `git checkout -b [nukeeper_branch_name]`
3. `git add --all` (or something alike)
4. `git commit -m ":package: Automatic update of [Package_name] to [New_package_version]"`
5. `git push` (or something alike)
6. (Open up pull request)
7. `git checkout master`

My suggestion would be:
1. `git checkout master` (default branch)
2. `git pull`
3. `git checkout -b [nukeeper_branch_name]`
4. `git add --all` (or something alike)
5. `git commit -m ":package: Automatic update of [Package_name] to [New_package_version]"`
6. `git push` (or something alike)
7. (Open up pull request)
8. `git checkout master`

Or we could merge master in on a later moment. I am willing to open up a pull request.

Developers can see the merge conflicts directly when checkout out NuKeeper's branch and do not have to manually checkout and merge master into NuKeeper's branch.

Ideas on this?

**Comment by MarcBruins** [comment]
This is done in the extension
