### ISSUE TITLE
Azure DevOps 'Commit message has exceeded the maximum size.'.

### ISSUE THREAD

**Issue by MaxMommersteeg** [NuKeeperDotNet/NuKeeper#621]
A pull request was created by NuKeeper (from Azure DevOps extension) and I am getting following message when clicking the `Set auto-complete` or `Complete` button on the pull request:
>Commit message has exceeded the maximum size.

![azuredevops_set_autocomplete](https://user-images.githubusercontent.com/9657173/50330740-a6e7f580-04fc-11e9-8c84-06c4f73b665c.png)

Following user voice could be related. However raising the character size will not always fix this issue. NuKeeper could potentially update thousands of packages in one go.
https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/20217283-raise-the-character-limit-for-pull-request-descrip

Maybe we can limit character count in some way when dealing with Azure DevOps or have settings per platform? For now I will decrease the message size manually.

**Comment by MaxMommersteeg** [comment]
Had a quick look at the source and come up with a small idea for resolving this issue.

Create an interface at `NuKeeper.Abstractions` called `ICommitWorder`. Have it specify the following signatures:
* `string MakePullRequestTitle(IReadOnlyCollection<PackageUpdateSet> updates);`
* `string MakeCommitMessage(PackageUpdateSet updates);`
* `string MakeCommitDetails(IReadOnlyCollection<PackageUpdateSet> updates);`

Rename `CommitWording` from `NuKeeper` to `DefaultCommitWording` and have it implemented `ICommitWorder`.

Add the following property to `CollaborationFactory`:
* `public ICommitWorder CommitWorder { get; private set; };`
Have it by default set to an instance of `DefaultCommitWording`. Default implementation could be overridden in `CollaborationFactory.CreateForPlatform` function.

We can then make other platform specific implementations of `ICommitWorder`. For example: `AzureDevOpsCommitWording`.

**Comment by MarcBruins** [comment]
Will have a closer look soon, not now due to holidays

**Comment by MarcBruins** [comment]
Could you make a start on this @MaxMommersteeg?

**Comment by MaxMommersteeg** [comment]
Sure I'll try to have a concept PR open this weekend.

**Comment by MaxMommersteeg** [comment]
A bit later than expected, but opened up an initial pull request ready for review.

**Comment by MaxMommersteeg** [comment]
Fixed with https://github.com/NuKeeperDotNet/NuKeeper/pull/665.
