### ISSUE TITLE
Repository Urls duplication

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#633]
The class `NuKeeper.Abstractions.CollaborationModels.Repository` has both `CloneUrl` and `HtmlUrl` (both of type URI).

We are only set up to clone using libgit2sharp from http(s) urls, not from ssh urls.

We should try to clarify which one should be used when. And if they overlap, could even remove one?

As noticed in #632

**Comment by MaxMommersteeg** [comment]
This is fixed right?
