### ISSUE TITLE
NuKeeper fails to run on Azure DevOps when a repositories size is greater than int.MaxValue

### ISSUE THREAD

**Issue by sanderaernouts** [NuKeeperDotNet/NuKeeper#661]
We have a few repositories for which we use [VFS for git](https://www.vfsforgit.org/). These repositories are >100 GB and do not contain code but other types of data.

When running NuKeeper against an Azure DevOps account that contains at least one git repository whose size is bigger than `int.MaxValue` the following exception occurs:
![image](https://user-images.githubusercontent.com/6184673/51658422-4c80ff80-1fa8-11e9-9bcc-57e095514cd7.png)

This is caused by a repository with a size of `51630689921`:
![image](https://user-images.githubusercontent.com/6184673/51658522-9a960300-1fa8-11e9-9350-e79d3e29103b.png)

I was able to fix it by changing the `Size` property of `AzureRepository` from `int` to `long`, I will submit a PR for this.

**Comment by shep1987** [comment]
This has been release in 0.15.0 Let us know if you have any further issues :)
