### ISSUE TITLE
"days ago" shouldn't only consider the newest version

### ISSUE THREAD

**Issue by OneCyrus** [NuKeeperDotNet/NuKeeper#663]
let's say we have a nuget package which has frequent releases e.g.:

```
1.0.0      12 days ago
1.0.1      10 days ago
1.0.2      7 days ago
1.0.3      5 day ago
1.0.4      3 day ago
1.0.5      2 day ago
1.0.5      1 day ago
...
```

our project has a reference to 1.0.0 and our nukeeper config has a 7 day threshold. the package will actually never get updated because the newest version will never be over the threshold. so with a 7 day threshold i would actually prefer if nukeeper would create a PR with version 1.0.2 so that we still move forward.

**Comment by AnthonySteele** [comment]
Why is version `1.0.2` considered good? In the general case, if a package is replaced 3 days later that's a strong indication that it had problems. In this special case you might want e..g. `--age 1d`

**Comment by OneCyrus** [comment]
we have some packages which have a very fast continuous integration strategy for releasing. but there are other packages which have the usual bigger releases where it's preferable to wait longer. but you're right it's probably quite hard to get this right as everything depends on the release strategy of each package. maybe we need a semver aware delay. minor version 7 days and patch version a rollforward option or something like that

**Comment by acraven** [comment]
@OneCyrus We have solved this before by having different pipelines for packages with different update cadences. It's possible to use the include/exclude arguments with different age and change arguments.

Third party packages we would use something like minor 7d, but for internal packages perhaps major 0d.
