### ISSUE TITLE
Use of outputfilename results in an error

### ISSUE THREAD

**Issue by BlackstarSolar** [NuKeeperDotNet/NuKeeper#676]
The [Configuration wiki page](https://github.com/NuKeeperDotNet/NuKeeper/wiki/Configuration) lists _outputfilename_ as a command line parameter but using it generates an error.

`> .\.tools\nukeeper.exe Inspect --outputfilename myfile.csv
Specify --help for a list of available options and commands.
Unrecognized option '--outputfilename'`

The correct term according to the [CommandBase class](https://github.com/NuKeeperDotNet/NuKeeper/blob/98fcd5e7b29244efbf7446f697dc0e407c88474e/NuKeeper/Commands/CommandBase.cs#L72) is _outputfile_ which works as expected.

Suggest either wiki is updated or code is changed to match wiki.

**Comment by AnthonySteele** [comment]
It looks like the wiki is incorrect. Well spotted.
