### ISSUE TITLE
Document environment variable used for git clone destination

### ISSUE THREAD

**Issue by david-mitchell** [NuKeeperDotNet/NuKeeper#683]
Currently, NuKeeper appears to perform `git clone`s to a folder inside `%APPDATALOCAL%\Temp\NuKeeper`.

I'm trying to run NuKeeper on a CI server shared by several teams at my organization, and I'd like to keep it as self-contained as possible. It would be cool to have an option to explicitly choose the location at which NuKeeper will perform `git clone` operations.

Alternatively, if such a mechanism already exists, it would be cool to document it.

**Comment by AnthonySteele** [comment]
We should document this, but we use [GetTempPath](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath), which can be controlled with environment variables as documented there.
