### ISSUE TITLE
Checkout branch before inspecting nuget packages

### ISSUE THREAD

**Issue by tectac** [NuKeeperDotNet/NuKeeper#694]
Hi,

I'm trying to target a specific branch in my repo so nukeeper can clone the repo, checkout this branch, upgrade packages and eventually create a PR under this branch.

To acheive this, I'm using the following command:
`nukeeper repo https://github.com/xxx/repo token --targetBranch origin/develop --fork SingleRepositoryOnly --exclude ^RavenDB --age 0  --consolidate --verbosity D`

It seems this command uses the master branch for nuget package inspection. Is there a way to force it to use another branch?

Thx
Sebastien

**Comment by MarcBruins** [comment]
Can you try without the 'origin' in targetbranch?

**Comment by tectac** [comment]
I see. A quick workaround for me was to change the default branch used in github.
Thx
