### ISSUE TITLE
Config in the repo

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#700]
It was suggested  by @zubivan  that NuKeeper's handling of a repo should be configurable by a file stored in that repo, in the way that `.editorconfig`, `nuget.config` or `.gitconfig` acts locally.

We have [a config file](https://github.com/NuKeeperDotNet/NuKeeper/wiki/Configuration#options-stored-in-file). but that is found "in the current folder", i.e. where nukeeper is run.

Many settings such as include / exclude filters are set on a "per repo" basis, so a file in that repo is a logical choice for this config. The `api` setting is the main exception to this.

In cases where `nukeeper repo` is run and the first action is to pull the repo files, the current folder cannot be in the repo, so the current config file mechanism won't work.

Proposal: At the point where this is possible, additionally check the repo root for a config file, and if found, read it into config.

Drawbacks: 
* this might mean changing config state after a run has started.
* the config file in a repo can't specify an `api` used to pull that repo, as that is needed earlier. 
* precedence rules are more complicated if the same value is specified in yet another way. Command line currently takes precedence over config file. Does it do that for a file in the repo? That could be hard to implement as once the config is built up, we no longer track the source of a value in the fallback of commandline, file, default.

**Comment by zubivan** [comment]
Should we try to come up with what should go into this config file?

> The api setting is the main exception to this.

I'd say not necessarily, it seems like the easiest way to just run `nukeeper.exe` in the root of the workspace. It will read the config by default, find outdated packages and create merge requests. :thinking:

**Comment by AnthonySteele** [comment]
It depends on the workflow that you are using. 
If the nukeeper run begins with cloning the repo, then you need the api base before that.

**Comment by zubivan** [comment]
So, that's I guess a design decision. We can probably support both workflows by saying that arguments coming from command line override those in the config?

**Comment by zubivan** [comment]
Was scanning through the issues and maybe we can also address this one https://github.com/NuKeeperDotNet/NuKeeper/issues/568 as a part of this story.

**Comment by AnthonySteele** [comment]
Yep, there is some synergy between those features.
