### ISSUE TITLE
Clear error when not providing a correct PAT

### ISSUE THREAD

**Issue by MarcBruins** [NuKeeperDotNet/NuKeeper#725]
So when running NuKeeper on `bitbucket` with a incorrect PAT. This is the message it throws:

```
User name missing from profile, falling back to .gitconfig
No pushable fork found for {project} in mode SingleRepositoryOnly
No pushable fork found for {repo}
```

It's probably the same for some of the others platforms. We should have a message that tell us that the we cannot authenticate.

**Comment by jbusuttil83** [comment]
I am having this issue as well. 
I created the password token from bitbucket and was getting this error. Debugged the application and it is getting 401.
Will have to check access again
