### ISSUE TITLE
Issues updating FluentValidation nuget package

### ISSUE THREAD

**Issue by TraGicCode** [NuKeeperDotNet/NuKeeper#727]
Nukeeper is informing me that the `FluentValidation` nuget package is outdated but when i ask it to update only that package it doesn't modify the csproj and simply outputs the outdated status again.

```
> nukeeper update --include FluentValidation 
```

**Comment by AnthonySteele** [comment]
Changes can fail if the solution structure causes issues. What happens if you add `--verbosity detailed` ? - that might make the issue clearer. What happens if you try to apply the update manually?
