### ISSUE TITLE
--targetBranch does not work with Github

### ISSUE THREAD

**Issue by Chama-StephanTuinder** [NuKeeperDotNet/NuKeeper#728]
Hi,
With update #697 the parameter --targetBranch is not stored anymore for GitHub

Simple solution: 
Change in GitHubSettingsReader.cs: 
public RepositorySettings RepositorySettings(Uri repositoryUri, string targetBranch = null)
{
....
            return new RepositorySettings
            {
                ApiUri = new Uri("https://api.github.com/"),
                RepositoryUri = repositoryUri,
                RepositoryName = repoName,
                RepositoryOwner = repoOwner,
                RemoteInfo = ( targetBranch != null ? new RemoteInfo() { BranchName = targetBranch } : null )
};

and in RepositoryUpdater.cs:
        private static void GitInit(IGitDriver git, RepositoryData repository)
        {
            git.Clone(repository.Pull.Uri);
            repository.DefaultBranch = repository.DefaultBranch ?? git.GetCurrentHead();
            git.Checkout(repository.DefaultBranch);
            git.AddRemote(repository.Remote, repository.Push.Uri);
        }

After that --targetBranch "origin/release/0.1.0" will work.
[targetBranchForGitHub.zip](https://github.com/NuKeeperDotNet/NuKeeper/files/3081038/targetBranchForGitHub.zip)

**Comment by MarcBruins** [comment]
I'm curious to why you want this functionality? I designed it specially for azure devops extension because that works with a detached head mode. Isn't the normal repo command enough for you?

**Comment by Chama-StephanTuinder** [comment]
The company I work for wants to do the updating of the nugets in
feature-branches of different projects that work on the same feature.
In this way the update of one projects nugets will be populated automaticly
to the other projects wich work on the same feature.

I was asked to investigate if this was possible.

**Comment by MarcBruins** [comment]
Very interesting! That sounds like a valid case we could support. Feel free to make a PR. Would be nice if we enable the option on all the platforms, and not only on github and azure devops. Feel free to join our [gitter](https://gitter.im/NuKeeperDotNet/Lobby) channel if you need any assistance.

**Comment by Chama-StephanTuinder** [comment]
Would be nice if it wasexplainded why it was closed....

**Comment by slang25** [comment]
So sorry, I'm on a beach and I think one of my kids must have grabbed my phone

**Comment by StephanTuinder** [comment]
This one was fixed
