### ISSUE TITLE
Investigate --singleBranch clone option to speed up NuKeeper

### ISSUE THREAD

**Issue by MarcBruins** [NuKeeperDotNet/NuKeeper#731]
When doing a clone we get all the remote branches including there history. If there are projects that have a lot of long lived branches this will cost a lot more time. I think we can us the `--single-branch --branch {branchname} ` option as a default to speed things up.

Some info here: https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---no-single-branch

**Comment by Chama-StephanTuinder** [comment]
Actually it is: --single-branch --branch {branchname}

**Comment by MaxMommersteeg** [comment]
This should be even easier to implement with https://github.com/NuKeeperDotNet/NuKeeper/pull/800 begin merged right?

**Comment by MarcBruins** [comment]
This should indeed be possible now with the #800

**Comment by AnthonySteele** [comment]
Should be useful
