### ISSUE TITLE
multiple Nukeeper instances won't run in parallel because of the cleanup action of the temp folders that is build in at startup

### ISSUE THREAD

**Issue by Chama-StephanTuinder** [NuKeeperDotNet/NuKeeper#738]
## 🐛 Bug Report

multiple Nukeeper instances won't run in parallel because of the cleanup action of the temp folders that is build in at startup.
(One inctance will (try to) cleanup a temp folder of the other which results in both of them crashing)

### Expected behavior
NuKeeper should be able to run in parallel

### Reproduction steps
Run 2 instances of NuKeeper at the same time, with the same account, on the  same machine.

### Configuration

**Version:** 0.21.1

**Platform if applicable:** 
- [X] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: Github
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

### Suggested solution:

Only delete temp folders that are older than lets say: 1 day.

**Comment by MarcBruins** [comment]
I think this is more a feature request then a bug to be honest. How could we fix these do you think?

**Comment by Chama-StephanTuinder** [comment]
the first action NuKeeper does is:
(CollaborationEngine.cs, line 35)
            _folderFactory.DeleteExistingTempDirs();

This routine deletes ALL temp folders created in the NuKeeper temp folder, also the ones that are used at the moment. I think it is build in to cleane out folders that are left after crashes of nukeeper.

Solution would be to check the create-time of the folders and only clear folders that are e.g. older than 1 day as NuKeeper wouldn't be running for a whole day.

**Comment by Chama-StephanTuinder** [comment]
issue fixed
