### ISSUE TITLE
Improve handling nuget update failures

### ISSUE THREAD

**Issue by pgrm** [NuKeeperDotNet/NuKeeper#760]
## 🚀 Feature Requests

It would be nice to improve the handling of errors when an update fails. Still submit a PR for all successful updates and add those errors as descriptions or comments to the PR.

### Contextualize the feature

We're running nukeeper on the whole organization for all repositories. Sometimes, things go south and because of one conflicting package, no PR is created, which is a petty, as we rely on those periodical PRs to keep the dependencies up to date.

Example error that we have:

```
  Restore completed in 37.98 ms for /PATH/Poject1.csproj.
  Restore completed in 41.73 ms for /PATH/Project2.csproj.
  Restore completed in 13.11 ms for /PATH/Project3.csproj.
  Restore completed in 2.72 ms for /PATH/Project4.csproj.
  Restore completed in 865.03 ms for /PATH/Project5.csproj.
/PATH/Project6.csproj : error NU1605: Detected package downgrade: Npgsql.EntityFrameworkCore.PostgreSQL from 2.2.0 to 2.0.0. Reference the package directly from the project to select a different version. 
/PATH/Project6.csproj : error NU1605:  Project6 -> Project5 -> Project4 -> Npgsql.EntityFrameworkCore.PostgreSQL (>= 2.2.0) 
/PATH/Project6.csproj : error NU1605:  Project6 -> Npgsql.EntityFrameworkCore.PostgreSQL (>= 2.0.0)
  Restore failed in 954.11 ms for /PATH/Project6.csproj.
```

We noticed it after enabling the `consolidate` flag, because the alternative was to merge way too many PRs - 2-3 PRs per repository on average, was just too painful and slow for us :disappointed: 

### Describe the feature

I guess what would be necessary is to do a restore after every file change to see if that restore works or not. If it fails, keep in in an internal list to afterwards add it to the gihtub PR, so people merging those PRs can decide if they want to manually fix it or not. The feature is obviously only needed when the flag `consolidate` is enabled

### Platforms affected (mark all that apply)
- [x] :hammer_and_wrench: NuKeeper CLI (this is what we use)
- [x] :sparkles: GitHub (this is what we use)
- [ ] :robot: AzureDevops
- [x] :checkered_flag: Bitbucket (probably also helpful for this platform)
- [x] :earth_americas: Gitlab (probably also helpful for this platform)
- [x] :tv: Gitea (probably also helpful for this platform)
- [ ] :whale: Docker

**Comment by timmkrause** [comment]
Actually I came here to file a bug regarding your error and/or to learn something about it and why it is happening. I have the same issue which actually happens quiet often (at an interval where the actual usage of NuKeeper is questionable, therefore I really have to fix this somehow).

Why is this even happening? 

NU1605 says "Reference the package directly from the project to select a different version." but in your case (same as mine) `Project6` already references the package directly.
Is it a follow-up failure?

Here is my log, just for the sake of completeness (ignore the "5 packages", I omitted them):

```
Found 5 possible updates
Microsoft.Extensions.Configuration.Binder from 3.0.0 to 3.0.1 in src\ProjectA\ProjectA.csproj
Microsoft.Extensions.Configuration.Binder from 3.0.0 to 3.0.1 in test\ProjectC\ProjectC.csproj

Found 5 package updates
Microsoft.Extensions.Configuration.Binder to 3.0.1 from 3.0.0 in 2 places since 6 days ago.
Selection of package updates: 5 candidates
Selected package update of Microsoft.Extensions.Configuration.Binder to 3.0.1
Updating 5 packages
'Microsoft.Extensions.Configuration.Binder' from 3.0.0 to 3.0.1 in 2 projects
Updates failed NuKeeperException : Command dotnet failed with exit code: 1

Attempted 5 updates and did 0
  Restore completed in 227.07 ms for D:\a\1\s\src\ProjectIrrelevant\ProjectIrrelevant.csproj.
D:\a\1\s\src\ProjectA\ProjectA.csproj : error NU1605: Detected package downgrade: Microsoft.Extensions.Configuration.Binder from 3.0.1 to 3.0.0. Reference the package directly from the project to select a different version. 
D:\a\1\s\src\ProjectA\ProjectA.csproj : error NU1605:  ProjectA -> ProjectB -> ProjectC -> Microsoft.Extensions.Configuration.Binder (>= 3.0.1) 
D:\a\1\s\src\ProjectA\ProjectA.csproj : error NU1605:  ProjectA -> Microsoft.Extensions.Configuration.Binder (>= 3.0.0)
  Restore completed in 124.43 ms for D:\a\1\s\src\ProjectB\ProjectB.csproj.
  Restore failed in 395.01 ms for D:\a\1\s\src\ProjectA\ProjectA.csproj.
  Restore completed in 5.36 ms for D:\a\1\s\test\ProjectC\ProjectC.csproj.
```

**Comment by timmkrause** [comment]
Still waiting for an explanation here. Regularly happens to me for the mentioned configuration packages and I always have to update them manually.

**Comment by AnthonySteele** [comment]
Is `ProjectA` updated first?

It could be the ordering of the project updates - it looks like in the second example that the right thing to do is to update `Microsoft.Extensions.Configuration.Binder`  in `ProjectC`, then in `ProjectA`.

**Comment by timmkrause** [comment]
Hm. Is this a question for me? If so, how can I influence this?
