### ISSUE TITLE
Gitea Uri-issue for subdomain server addresses

### ISSUE THREAD

**Issue by sharpSteff** [NuKeeperDotNet/NuKeeper#762]
## 🐛 Bug Report
In case gitea is hosted on a subdomain like
https://yourserver/git/

the baseaddress is messed up and "/git/" will be removed, which causes no functionality 

### Expected behavior

gitea on subdomain should also work

### Reproduction steps

`nukeeper repo https://yourserver/git/Orga/Repo.git token --platform Gitea --fork PreferSingleRepository`

### Configuration

**Version:** 0.20.5

**Platform if applicable:** 
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [X] :tv: Gitea
- [ ] :whale: Docker

**Comment by MaxMommersteeg** [comment]
This issue can be closed right?

**Comment by sharpSteff** [comment]
Yes fixes

**Comment by MarcBruins** [comment]
Thanks guys!
