### ISSUE TITLE
Add option to update references only (no restore)

### ISSUE THREAD

**Issue by Roadrunner67** [NuKeeperDotNet/NuKeeper#765]
## 🚀 Feature Requests

It would be handy to be able to only update the referencing project files without actually restoring the packages.

### Contextualize the feature
Gives the opportunity to see the impact a lot quicker.
In some scenarios you would run nukeeper locally and let your CI/CD server restore and build.

**Comment by skolima** [comment]
The dotnet tooling does not support this scenario.

**Comment by MaxMommersteeg** [comment]
I created a (draft) pull request (https://github.com/NuKeeperDotNet/NuKeeper/pull/833). That branch removes the default of performing a `dotnet restore` before each package update. It also performs the `dotnet add package` command for updating a package with the `--no-restore` flag.

However, in the end we are still restoring all projects that received a package update.
