### ISSUE TITLE
Platform argument not followed unless repo URL matches satisfies the string pattern

### ISSUE THREAD

**Issue by ElanHasson** [NuKeeperDotNet/NuKeeper#798]
## 🔙 Regression

`Platform` config value is ignored unless the repository URL matches the string pattern in the platform `ISettingsReader` implementation.

### Old (and correct) behavior
Doesn't seem to have worked.

### Current behavior
Platform is ignored unless Repository URL matches the string pattern.

### Reproduction steps
`nukeeper repo https://myserver/projects/org/reponame token` fails because the URL doesn't match any of the platform `ISettingsReader` implementation.
`nukeeper repo --platform Bitbucketlocal https://myserver/projects/org/reponame token`  fails because there is no logic to short circuit the string pattern matching if platform is specified.

### Configuration

**Version:** 0.21.2

**Platform if applicable:** 
- [X] :hammer_and_wrench: NuKeeper CLI
- [X] :sparkles: GitHub
- [X] :robot: AzureDevops
- [X] :checkered_flag: Bitbucket
- [X] :earth_americas: Gitlab
- [X] :tv: Gitea
- [X] :whale: Docker

**Comment by ElanHasson** [comment]
See #590 also.

**Comment by jwmoffat** [comment]
I can confirm this as well.  

I've been trying to get it to work on version 0.21.3 with gitlab.  

Without any flag, I get the error "Unable to work out which platform to use [URL] could not be matched"

At first I thought I was setting the platform flag incorrectly, but if you give it an invalid option it prints out "Invalid value specified for platform. Allowed values are: GitHub, AzureDevOps, Bitbucket, BitbucketLocal, GitLab, Gitea"

However, even with a valid platform flag, I still get the same original error.

Changing my URL (via a hosts entry in Windows) to include "gitlab" in the URL then allows it to move forward.

**Comment by msallin** [comment]
There is currently an issue with our local Bitbucket installation, which prevents me from testing and I'm also not sure if I catched the root of the issue. Please review and test.

https://github.com/NuKeeperDotNet/NuKeeper/pull/821

**Comment by zubivan** [comment]
Also observed this behaviour, great that you're fixing it!

**Comment by StephanTuinder** [comment]
My 2 cents: It seems to be ignored in the "repo" mode

**Comment by msallin** [comment]
@ElanHasson close the issue?

**Comment by ElanHasson** [comment]
I haven't had a chance to revisit this. I'll close for now and reopen if I see it again
