### ISSUE TITLE
Git commandline as Lib2git alternative

### ISSUE THREAD

**Issue by sharpSteff** [NuKeeperDotNet/NuKeeper#799]
## 🚀 Feature Requests
Currently I'm facing some issues with Lib2Git(Sharp). It seems the git implementation differs from the native git implementation. Which results into bad (or not possible) repository interactions, e.g. when a (reverse) proxy is active or ssh-protocoll should be used.

I think it would be a great feature to give the user to possibility to enter the path to the git commandline as parameter in case the lib2git library is not enough

### Contextualize the feature
Second implementation of `IGitDriver `beside `LibGit2SharpDriver`

additional optional parameter `--gitcmdPath`, which is null per default

### Describe the feature
Implementation of a `GitCmdDriver : IGitDriver` which can be used as alternative to lib2sharpdriver.

Nukeeper should not ship git cmd, just give the option to use the installed git  

### Platforms affected (mark all that apply)
- [X] :hammer_and_wrench: NuKeeper CLI
- [X] :sparkles: GitHub
- [X] :robot: AzureDevops
- [X] :checkered_flag: Bitbucket
- [X] :earth_americas: Gitlab
- [X] :tv: Gitea
- [] :whale: Docker

**Comment by sharpSteff** [comment]
started implementation on my fork
3b372111c875a9f4fdb01a508189ede03f162ed7

**Comment by sharpSteff** [comment]
its crazy the proxy issue immediately disappeared when using git cli

**Comment by sharpSteff** [comment]
I stumbled over #659. Any information how this is ongoing?

**Comment by MaxMommersteeg** [comment]
I think this has been merged in. Can we close this issue?

**Comment by shep1987** [comment]
Thanks for the work!
