### ISSUE TITLE
Possibility to name the branch NuKeeper makes for adding the updates

### ISSUE THREAD

**Issue by StephanTuinder** [NuKeeperDotNet/NuKeeper#813]
## 🚀 Feature Requests
possibility to name the branch NuKeeper makes for adding the updates

### Contextualize the feature
By naming the branch NuKeeper creates, it is possible to make several runs of NuKeeper 
contribute to the same pullrequest.
Also it makes it possible to have a coherent naming of branches that belong to each other:
Nuget code updated for "AwsomeFeature". For all NuKeeper updates of this nuget the branch/pullrequest can also be named  "AwsomeFeature"

### Describe the feature
If the branchname is given, NuKeeper should check if this branch exists and skip creating the branch, if not, it should create the branch with the given name.
If the pullrequest exists on given branch NuKeeper should skip creating the pullrequest.

### Platforms affected (mark all that apply)
- [X] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by MarcBruins** [comment]
This is already possible with the `branchNamePrefix` parameter: https://nukeeper.com/basics/configuration/

**Comment by MaxMommersteeg** [comment]
I don't think that is the feature that @StephanTuinder wants. Say you have a working branch named `feature/foo` he wants to explicitly target the branch for NuKeeper updates. He doesn't only want to add a prefix to generated branch name, but also to just specify the branch name that gets created entirely.

**Comment by StephanTuinder** [comment]
@MaxMommersteeg  Correct

**Comment by MaxMommersteeg** [comment]
Besides from more control over branch naming, does this introduce any other functionality that isn't available right now with [target branch option](https://nukeeper.com/commands/repository/#using-a-targetbranch)?

**Comment by Chama-StephanTuinder** [comment]
targetbranch option selects the branch Nukeeper will run against. I propose a feature with which you can determine what the nukeeper branch will be named.

**Comment by batkaevruslan** [comment]
It would be great as we have branch name checks for Pull Requests.

**Comment by StephanTuinder** [comment]
PR is waiting to be approved for this: #841
