### ISSUE TITLE
Is it possible to use Nukeeper with Xamarin projects?

### ISSUE THREAD

**Issue by EP01** [NuKeeperDotNet/NuKeeper#814]
## 💬 Questions and Help

Hi,

I'm looking at integrating Nukeeper with our Azure DevOps Server repositories, and it works really well for normal NetStandard libraries, etc. I'm just wondering if it's possible to use Nukeeper to update Xamarin projects? I don't think `dotnet restore` works for Xamarin projects, and they require the CLI (or msbuild) version of nuget to restore. Is there a parameter available to choose the restore method? I get the following error when running `nukeeper repo pat`.

```
error: The imported project "C:\Program Files\dotnet\sdk\2.2.104\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.C
Sharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

Thanks

**Comment by zubivan** [comment]
Hi @EP01 can you please make a small reproduction project for us?

**Comment by mauro-dasilva** [comment]
We are having the same issue. It seems that when it is doing a dotnet remove to remove the package, it throws an error like the following:

_In path D:\a\1\s\TestApp\TheApp.iOS, running command: dotnet remove TestApp.iOS.csproj package Microsoft.AppCenter
Command dotnet failed with exit code: 1

info : Removing PackageReference for package 'Microsoft.AppCenter' from project 'TestApp.iOS.csproj'.
error: The imported project "D:\a\_tool\dncs\2.2.301\x64\sdk\2.2.301\Xamarin\iOS\Xamarin.iOS.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\a\1\s\TestApp.iOS\TestApp.iOS.csproj_

From what I can see it is the following line in the .csproj file that is causing the issue:
`  <Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.CSharp.targets" />`

I think that for dotnet remove, the MSBuildExtensionsPath is different. Hence causing the issue?

**Comment by mauro-dasilva** [comment]
I have been trying to debug the issue and it seems that because Xamarin is using PackageReferences and doesnt support _dotnet restore_, it needs to use NuGet restore instead.

This is the part of the code that is saying that it is a ProjectFileOldStyle.

```
  return xmlNamespace.NamespaceName == VisualStudioLegacyProjectNamespace
                ? new PackagePath(baseDirectory, relativePath, PackageReferenceType.ProjectFileOldStyle)
                : new PackagePath(baseDirectory, relativePath, PackageReferenceType.ProjectFile);
```
I have attached a sample project which is failing.

[App1.zip](https://github.com/NuKeeperDotNet/NuKeeper/files/3404351/App1.zip)

**Comment by zubivan** [comment]
Hi @mauro-dasilva. Can you please make a small repo with a reproduction case?

**Comment by zubivan** [comment]
Hi @mauro-dasilva I looked into it, seems like indeed `<Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.CSharp.targets" />` is messing things up during an import. I've seen couple of thread on Xamarin forums describing the same problem with Nuget, I'd look a bit more later this week to see if there is anything we can do here.

**Comment by mauro-dasilva** [comment]
Cool, appreciate your efforts bud!

**Comment by mauro-dasilva** [comment]
Hey @zubivan just wondering if you have any update on this?
