### ISSUE TITLE
Include nuget commandline as a dependency

### ISSUE THREAD

**Issue by cohen990** [NuKeeperDotNet/NuKeeper#84]
Currently we rely on the user having nuget installed and installed in the correct place

https://www.nuget.org/packages/NuGet.CommandLine/

We can break that dependency by including nuget as a nuget package in true nugetception

**Comment by skolima** [comment]
Looks like I've missed it in https://github.com/NuKeeperDotNet/NuKeeper/pull/31/ , it was supposed to be there.
