### ISSUE TITLE
BitbucketLocal doesn't work

### ISSUE THREAD

**Issue by evolvedlight** [NuKeeperDotNet/NuKeeper#843]
## 🐛 Bug Report

It seems that this doesn't work anymore thanks to a new validation.
It just gives the error ""

### Expected behavior
As delete after merge isn't supported, it doesn't validate or try to do it

### Reproduction steps

λ NuKeeper.exe repo --platform bitbucketlocal http://bitbucket.ourcompany.com/scm/project/gitrepo.git token
Collaboration platform specified as 'BitbucketLocal'
Deletion of source branch after merge is currently only available for Azure DevOps, Gitlab and Bitbucket.

### Configuration

**Version:** 0.24.0

**Platform if applicable:** 
- [x ] :hammer_and_wrench: NuKeeper CLI
- [x ] :checkered_flag: Bitbucket

**Comment by msallin** [comment]
As far as I see, there are two problems here.
1) The default value for `DeleteBranchAfterMerge` is `true`, also if the target platform doesn't support this.
2) The validation is broken, therefore even if `DeleteBranchAfterMerge` is set to `false`, none of the not supported platforms are going to work.

I created a PR to fix it. Didn't had time to create Unit Tests but the method `PopulateDeleteBranchAfterMerge` should be tested well, as there are a lot of possible states which can occurred. Feel free to contribute: https://github.com/NuKeeperDotNet/NuKeeper/pull/844

**Comment by zubivan** [comment]
@msallin @evolvedlight should be resolved now.

**Comment by msallin** [comment]
Tested. It works.

**Comment by zubivan** [comment]
@msallin Thank you for taking a look!
