### ISSUE TITLE
Issue with Nuget packages that are updated frequently

### ISSUE THREAD

**Issue by seroche** [NuKeeperDotNet/NuKeeper#847]
Hi,

One of our projects is using the AWS S3 nuget package [https://www.nuget.org/packages/AWSSDK.S3/](here) 

Since AWS releases a new version 1-3 times a week, Nukeeper keeps on finding new versions and always postpone the update for 7 days. In that case, AWS Nuget packages never get updated.

Here is the command line we used (replace the `,` by `space`):
repo,https://github.com/XXX/lambda,token,--label,nuget,--consolidate,--exclude,^RavenDB,--source,https://api.nuget.org/v3/index.json

Logs from the container
```
Found 4 package updates
AWSSDK.Rekognition to 3.3.100.54 from 3.3.100.47 in 1 place since 5 hours ago.
Novell.Directory.Ldap.NETStandard to 3.0.0-beta5 from 3.0.0-beta4 in 1 place since 9 days ago.
AWSSDK.SQS to 3.3.100.54 from 3.3.100.45 in 1 place since 5 hours ago.
AWSSDK.S3 to 3.3.104.6 from 3.3.103.2 in 1 place since 5 hours ago.
Filtered by minimum package age '7 days ago' from 4 to 1
Filtered by remote branch check branch from 1 to 0
Selection of package updates: 4 candidates, filtered to 0
No updates can be applied. Exiting.
```

Any idea on how we could workaround this issue?

Thx
Seb

**Comment by AnthonySteele** [comment]
Hello.

try adding `--age 2d` to the command line, to take packages once they have been out for 3 days.

The default setting is `7d`, to not take packages younger than 7 days, out of caution of bad releases, which usually get replaced. 

Some packages, e.g. the `AWS`  ones, and some companies internal packages, release faster than this. So in this case you change it to a lower time such as `2w` for 2 weeks, `3d` for 3 days,  `12h` for 12 hours, or `0` if you want to live on the bleeding edge.

I have seen runs that are specially for AWS packages, with a lower threshold, e.g. `--include AWS --age 2d`

**Comment by seroche** [comment]
Hi Antony,

Thx for your help. I will probably make a specific script for AWS packages. 

In the meantime, would it be possible to change the behaviors associated to the `age` parameter. It would be great to have the ability to specify that `major` releases or `minor or higher` releases or `patch or higher` releases that are older than N days should be returned.

Example
Parameters `--min-change Patch --age 7d` would produce the following behaviors:

```
Currently installed package version 3.3.103
3.3.103.1 >> Ignored
3.3.103.2 >> Ignored
3.3.103.3 >> Ignored
3.3.103.4 >> Ignored
3.3.104 (if release was published more than 7d ago, create PR)
3.3.104.1 >> Ignored
3.3.104.2 >> Ignored
```

Do I make sense?

**Comment by Bouke** [comment]
So conceptually NuKeeper waits for a package to stabilise, to prevent issues with bad releases. This requires a package to publish a stable release. In your example, the algorithm doesn't consider 3.3.104 as it has been replaced with a newer version. It might be possible that 3.3.104 is a bad release and we shouldn't pick it. This would happen for any package that publishes new versions within whatever combination of `age` and `min-change` you specify.

So the question becomes: when to mark a release as "not bad" when it is frequently released?

**Comment by Bouke** [comment]
Why auto-close the ticket?

**Comment by Bouke** [comment]
Why auto-close the ticket?

**Comment by Bouke** [comment]
Why auto-close the ticket?
