### ISSUE TITLE
UPDATE command failing when project name has spaces in it

### ISSUE THREAD

**Issue by ewest305** [NuKeeperDotNet/NuKeeper#863]
## 🐛 Bug Report

Unhandled exception when UPDATE command is used against a repo having a project name with spaces in it. 

### Expected behavior
Should not cause unhandled exception

### Reproduction steps
Ensure there is a project name with space in it (example: "XCAD Framework.csproj")
Run Nukeeper Update command 
Following shows in console: 

> Nuget restore on C:\Users\ewest\Documents\securusps\xcad\Client\FrameWork XCAD Framework.csproj

> Unhandled Exception: NuKeeper.Abstractions.NuKeeperException: Command dotnet failed with exit code: 1
> 
> MSBUILD : error MSB1008: Only one project can be specified.
> Switch: Framework.csproj
> 
> For switch syntax, type "MSBuild -help"
> 
> 
> 
>    at NuKeeper.Update.ProcessRunner.ExternalProcess.Run(String workingDirectory, String command, String arguments, Boolean ensureSuccess) in C:\Users\ewest\source\repos\NuKeeper-master\NuKeeper.Update\ProcessRunner\ExternalProcess.cs:line 63
>    at NuKeeper.Update.Process.DotNetUpdatePackageCommand.Invoke(PackageInProject currentPackage, NuGetVersion newVersion, PackageSource packageSource, NuGetSources allSources) in C:\Users\ewest\source\repos\NuKeeper-master\NuKeeper.Update\Process\DotNetUpdatePackageCommand.cs:line 28
>    at NuKeeper.Update.UpdateRunner.Update(PackageUpdateSet updateSet, NuGetSources sources) in C:\Users\ewest\source\repos\NuKeeper-master\NuKeeper.Update\UpdateRunner.cs:line 52
>    at NuKeeper.Local.LocalUpdater.ApplyUpdates(IReadOnlyCollection`1 updates, IFolder workingFolder, NuGetSources sources) in C:\Users\ewest\source\repos\NuKeeper-master\NuKeeper\Local\LocalUpdater.cs:line 67
>    at NuKeeper.Local.LocalUpdater.ApplyUpdates(IReadOnlyCollection`1 updates, IFolder workingFolder, NuGetSources sources, SettingsContainer settings) in C:\Users\ewest\source\repos\NuKeeper-master\NuKeeper\Local\LocalUpdater.cs:line 56
>    at NuKeeper.Local.LocalEngine.Run(SettingsContainer settings, Boolean write) in C:\Users\ewest\source\repos\NuKeeper-master\NuKeeper\Local\LocalEngine.cs:line 62
>    at NuKeeper.Commands.UpdateCommand.Run(SettingsContainer settings) in C:\Users\ewest\source\repos\NuKeeper-master\NuKeeper\Commands\UpdateCommand.cs:line 52
>    at NuKeeper.Commands.CommandBase.OnExecute() in C:\Users\ewest\source\repos\NuKeeper-master\NuKeeper\Commands\CommandBase.cs:line 104
>    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
>    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
>    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
>    at NuKeeper.Program.Main(String[] args) in C:\Users\ewest\source\repos\NuKeeper-master\NuKeeper\Program.cs:line 33

### Configuration

**Version:** 0.25.0

**Platform if applicable:** 
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [x] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by ewest305** [comment]
I was able to get around this by escaping the quote character around the projectFileName variable in Invoke method in NuKeeper.Update\Process\DotNetUpdatePackageCommand.cs.

**Comment by buckstephenh** [comment]
Just encountered this problem.  Lame.

**Comment by timmkrause** [comment]
@buckstephenh Switch to Dependabot or Renovate. NuKeeper is dead.
