### ISSUE TITLE
.NET Core 3.0 support

### ISSUE THREAD

**Issue by skolima** [NuKeeperDotNet/NuKeeper#876]
It's officially available and stable now. Current results when installing NuKeeper with 3.0 available (and not 2.1):

```
You can invoke the tool using the following command: nukeeper
Tool 'nukeeper' (version '0.25.0') was successfully installed.
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
- The following frameworks were found:
 3.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The .NET Core frameworks can be found at:
 - https://aka.ms/dotnet-download
```

**Comment by AnthonySteele** [comment]
Looks like in 2.1. and 2.1 you don't get c#8
( here https://dotnet.microsoft.com/download/dotnet-core/2.2 and here https://dotnet.microsoft.com/download/dotnet-core/2.1 "Supports C# 7.3"  )

So if we want not-nullable reference types (which we might, it's a good feature) we have to go to .NET Core 3.0 only. But could target both in the interim?

**Comment by slang25** [comment]
C# 8.0 is unsupported, there are some workarounds you can apply to get most features working, but I'd advise against it. I think it would be best to target core 2.1 & 3.0 for now, then in a few months drop 2.1

**Comment by tectac** [comment]
Does this mean we do not have the ability to auto update packages added to `.net core 3.0` projects?

Currently I get the following errors if I try to do that:

```
Updates failed NuKeeperException : Command dotnet failed with exit code: 1

/usr/share/dotnet/sdk/2.2.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/tmp/NuKeeper/repo-29bfe4e757554c98bbb620122ac2ab68/src/TEC.CoreServiceVerification.Infrastructure/TEC.CoreServiceVerification.Infrastructure.csproj]
/usr/share/dotnet/sdk/2.2.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/tmp/NuKeeper/repo-29bfe4e757554c98bbb620122ac2ab68/src/TEC.CoreServiceVerification.Application/TEC.CoreServiceVerification.Application.csproj]
```

**Comment by Maxwe11** [comment]
@AnthonySteele when do you plan to publish new version?

**Comment by Maxwe11** [comment]
@AnthonySteele is there anything we can do to proceed with publishing new version?

**Comment by dcook-net** [comment]
Just as an FYI for any consumers looking for a temporary work around, I have had quite a bit of success in over coming this issue using Docker. 

By using a 3.1 SDK base image, and then installing the 2.1 SDK on top, then layering NuKeeper on top.

Can share the Dockerfile if anyone want's it....it's not pretty by any stretch, but it gets the job done.

**Comment by Maxwe11** [comment]
Hey there, this issue has been resolved and now Nukeeper works fine on .Net Core 3.1 so it could be closed now.
