### ISSUE TITLE
NuGet restore fails

### ISSUE THREAD

**Issue by nickdalt** [NuKeeperDotNet/NuKeeper#878]
## 🐛 Bug Report

 
Running the nukeeper repo command on a repository with the following structure:-

- SolutionDir
-- Solution.sln
-- ProjectA.vcxproj
-- packages.config
-- packages  
-- ProjectBDir
--- ProjectB.vcxproj
--- packages.config

Where projects A and B are in the solution, nukeeper fails when running nuget restore on projectB packages.config from within the ProjectBDir.

The error from nuget is that -PackagesDir or -SolutionDir needs to be specified.

### Expected behavior

nuget restore is executed successfully for both package.config files, the nuget dependencies are updated, and the a pull request is created.

### Reproduction steps

As above

### Configuration

As above

**Version:** master/HEAD

**Platform if applicable:** 
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [x] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by zubivan** [comment]
@nickdalt Hi there, can you please create a small repro project for us? A a github repo will do.

**Comment by nickdalt** [comment]
See https://github.com/nickdalt/NuKeeperIssue878.git

**Comment by zubivan** [comment]
Seems related to #72
