### ISSUE TITLE
Improvements for CI Support

### ISSUE THREAD

**Issue by nickdalt** [NuKeeperDotNet/NuKeeper#882]
## 🏗 Enhancement Proposal

NuKeeper as currently written is problematic when trying to use it for CI purposes.

- It makes the assumption that Git is configured as it would be on a developers machines. i.e. user and email set in git config. However, this is not necessarily the case on a build machine.
- I makes assumptions about where NuGet.exe might be located which again is not necessarily true on a build machine.
- When it fails to perform its function it does not return a suitable exit code to enable the build process to take suitable actions. In most config parsing situations it appears to return 0.

These assumptions are not documented and only evident if you spend some time looking at the code or by debugging.

### Pitch

I suggest the following improvements:-

- Remove the need for Git configuration. Maybe use defaults such the user you already have from the creds and nukeeper@github.com as the email. Failing that allow the values to be specified on the command line.
- Allow the nuget.exe path to be specified on the command line.
- Only return 0 if the program is entirely successful at updating the packages.config etc and creating the PR or if there is nothing to do. Otherwise return some error value.

### Platforms affected (mark all that apply)
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by AnthonySteele** [comment]
Related to #988 930
