### ISSUE TITLE
Incorrect handling of conflicts during update

### ISSUE THREAD

**Issue by nickdalt** [NuKeeperDotNet/NuKeeper#889]
## 🐛 Bug Report

If there are conflicts during the update process, the action taken is not necessarily the correct one due to the default behaviour of the FileConflictAction.

In my particular case a content item is added to the project when the nuget package is added. When nukeeper runs and updates the project, the outcome is that the content item is deleted from the git repo instead of being updated.

I would suggest allowing the user to specify the FileContentAction nuget parameter on the nukeeper command line. Alternatively, add the parameter by default specifying overwrite as the default.

### Expected behavior

The content item from the nuget package is not deleted from the git repo

### Reproduction steps

1. NuGet package containing a content item e.g package.natvis which is checked in to git.
2. Run nukeeper so that the project containing the package is updated

### Configuration

**Version:**  HEAD

**Platform if applicable:** 
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CrispyDrone** [comment]
@nickdalt 

How is it possible that it is deleting the file? I can only find `Ignore`, `Overwrite`, and `PromptUser` as actions. See <https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-update>.

There has been a similar issue where someone thought a file was deleted, but instead its casing had changed. Windows doesn't consider casing changes significant, but linux does. Could you confirm this is not what happened?

Also just out of curiosity what is `package.natvis`? It would be helpful if you could share a link to this nuget package (?) or maybe a nuget package that has a content file (and displayed this behavior).
