### ISSUE TITLE
Allow to set custom PR message and header

### ISSUE THREAD

**Issue by SuddenGunter** [NuKeeperDotNet/NuKeeper#897]
## 🚀 Feature Requests

Allow to set custom PR message and header when use `nukeeper repo`

### Contextualize the feature
Various projects may have various needs. On my current projects all PR's follow same template, for example if developers wants to merge PR with jira task resolved he/she must submit it with `JIRA_TICKET: description` this header and specific description. Why not do same with NuKeeper's PRs?

### Describe the feature
I propose to split it in multiple features maybe:
- allow to set custom PR header template (i.e. `NUKEEPER: update {from} {to}`) - it must be not just header, but template which will be enriched with values later when nukeeper creates PR;
- allow to set custom PR message template;

### Platforms affected (mark all that apply)
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CrispyDrone** [comment]
I have a pull request open for this [here](https://github.com/NuKeeperDotNet/NuKeeper/pull/1048)
