### ISSUE TITLE
Filter and label open issues

### ISSUE THREAD

**Issue by SuddenGunter** [NuKeeperDotNet/NuKeeper#898]
## 🏗 Enhancement Proposal

At the moment there are almost 50 issues, and many of them contain no labels.
Labels help potential contributors to find issues where their help may be needed. Last month during hacktoberfest I used http://issuehub.io/ to find issues by labels like "good first issue" (first-time open-source contributor) and programming language.  
If we add labels now - it will potentially increase community engagement. 

### Pitch

More new contributors, more new ideas, features delivered faster, bugs squashed faster

### Platforms affected (mark all that apply)
- [ ] :hammer_and_wrench: NuKeeper CLI
- [x] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CrispyDrone** [comment]
Also, stale bot shouldn't be closing issues. It should just mark them as "stale". Even the "wontfix" label is too drastic in my opinion.
