### ISSUE TITLE
Executable isn't returning failure code when a failure occurs

### ISSUE THREAD

**Issue by sapeavy** [NuKeeperDotNet/NuKeeper#904]
I'm using NuKeeper as a task within Azure DevOps. When the executable never gives a failure return code the task doesn't fail and I never know when my automated process needs attention.

**Comment by Bouke** [comment]
Just to document some failure modes, here's a failure when restoring packages that returns a 0 exit code:
```
Updating 'Microsoft.CodeAnalysis.VersionCheckAnalyzer' from 2.9.4 to 2.9.8 in 1 projects
Nuget restore on d:\a\1\s\Source\NODEJSPROJECT packages.config
Updates failed NuKeeperException : Command C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe failed with exit code: 1

MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.


Unable to locate project file for 'd:\a\1\s\Source\NODEJSPROJECT\packages.config'.

Attempted 3 updates and did 0
##[section]Finishing: NuKeeper
```

**Comment by CrispyDrone** [comment]
For collaboration commands (`repo`, `global`, `organization`), this should now be fixed by https://github.com/NuKeeperDotNet/NuKeeper/pull/1058
