### ISSUE TITLE
NuGet.config not found

### ISSUE THREAD

**Issue by Bouke** [NuKeeperDotNet/NuKeeper#907]
## 🐛 Bug Report

`NuGet.config` is located at `.nuget\NuGet.config` in a subfolder containing the solution file. This `NuGet.config` file is not picked up.

### Expected behavior

I would expect the `NuGet.config` to be picked up, as does Visual Studio.

### Reproduction steps

I have the following file structure:

```
(root)
\- Source
    |- .nuget
    |   \- NuGet.config
    \- Solution.sln
```

### Configuration

**Version:** nukeeper 0.26.0 x64

**Platform if applicable:** 
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by Bouke** [comment]
Why auto-close the ticket?

**Comment by Bouke** [comment]
Why auto-close the ticket?

**Comment by Bouke** [comment]
Why auto-close the ticket?

**Comment by CrispyDrone** [comment]
It seems this behavior has changed between nuget 3.3 and later versions: https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses

**Comment by Bouke** [comment]
Thank you! That seems to be the culprit here:

> NuGet 3.3 and earlier used a .nuget folder for solution-wide settings. This folder is not used in NuGet 3.4+.
