### ISSUE TITLE
Patch version demand not being respected?

### ISSUE THREAD

**Issue by CrispyDrone** [NuKeeperDotNet/NuKeeper#912]
## 🐛 Bug Report
I'm using the parameter `--change Patch` but it seems that in certain cases minor version updates are being chosen.

### Expected behavior
When I specify `--change Patch`, I expect only patch updates of packages to be applied in all cases.

### Reproduction steps
1. Use the following command `nukeeper repo <url> <token> --change Patch`

### Configuration

**Version:** 0.26.0

**Platform if applicable:** 
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [X] :robot: AzureDevops (TFS 2017)
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

### Extra information
1. Pull request description

```
  NuKeeper has generated a minor update of NLog to 4.5.11
  2 versions of NLog were found in use: 4.3.2, 4.3.1
  NLog 4.5.11 was published at 2018-11-06T17:31:25Z, 1 year and 1 month ago
  There is also a higher version, NLog 4.6.8 published at 2019-11-04T21:35:02Z, 1 month ago, but this was not applied as only Patch version changes are allowed.
```

2. Logfile: [nukeeper-log-2019-12-13.txt](https://github.com/NuKeeperDotNet/NuKeeper/files/3962718/nukeeper-log-2019-12-13.txt)

  An excerpt:

```
EntityFramework from 6.1.3 to 6.2.0 in ************.SPC.WebApi.Tests\packages.config

EntityFramework.SqlServerCompact.Legacy from 6.1.3 to 6.2.0 in ************.SPC.WebApi.Tests\packages.config
```

**Comment by CrispyDrone** [comment]
I don't like creating useless bump posts, but I guess stale bot leaves me no choice.

**Comment by CrispyDrone** [comment]
Bump.

**Comment by furlongmt** [comment]
Hi, I'm also facing this issue and due to our project setup, we cannot use Nukeeper until this bug is fixed. Could someone please review this PR (Thanks @CrispyDrone!)

**Comment by furlongmt** [comment]
Thank you for promptly merging the PR. When can we expect the next version of Nukeeper (with this bug fix included) to be available?

**Comment by phatcher** [comment]
@CrispyDrone Is this finished now that the code has been merged?

**Comment by CrispyDrone** [comment]
@phatcher I haven't experienced any issues regarding this any more, so I would say yes.

I'll close the issue.
