### ISSUE TITLE
Repo Command Deleted File

### ISSUE THREAD

**Issue by JarrodJ83** [NuKeeperDotNet/NuKeeper#914]
## 🐛 Bug Report
Tried NuKeeper for the first time today so maybe I am missing something but I would never expect this to delete any of my files. I simply ran a repo command and one code files was deleted by it.

### Expected behavior
PR Opened up with **_only_** package changes

### Reproduction steps
Run repo command on a BitBucket.org repo:
`nukeeper repo https://<user>@bitbucket.org/<team>/project.git token --consolidate`

PR opened up with package changes and a deleted .cs file
![image](https://user-images.githubusercontent.com/248166/71209336-3db6d180-2279-11ea-8f12-13193525130c.png)

### Configuration

**Version:** 0.26.0

**Platform if applicable:** 
- [ x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ x] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by JarrodJ83** [comment]
This is reproducible. I would love to use NuKeeper but can't until this is addressed. Is there anything more I can do or provide to get some traction on this?

**Comment by AnthonySteele** [comment]
That's very odd - is this a generated file? What happens to it when you use `dotnet` or `nuget`  commandlines to update packages?

**Comment by JarrodJ83** [comment]
I will try to run reproduce this again this week with latest version of NuKeeper and provide more details. Thanks, @AnthonySteele !

**Comment by AnthonySteele** [comment]
Is it the only file in the folder? what is the path (relative to the .sln file) 
Is it an artefact that comes out of a package?
Basically, what's so special about _this_ file?

**Comment by JoeRichSoftware** [comment]
We saw similar behaviour when running against one of our repos.  Investigating our deleted file we found the file existed in our git repo twice in matching (when case insensitive) paths.  for example:
c:\Dev\file.cs
c:\dev\file.cs

`dotnet`, `nuget `and Visual studio had no complaints so we hadnt noticed it before.

**Comment by JarrodJ83** [comment]
@JoeRichSoftware looks like that was the issue here! Thanks! Looks like just an issue with Git and not Nukeeper then, @AnthonySteele ?
