### ISSUE TITLE
xamarinmac20 packages have their hint path incorrectly changed to netstandard2.0

### ISSUE THREAD

**Issue by ghelyar** [NuKeeperDotNet/NuKeeper#927]
## 🐛 Bug Report

I was using `Microsoft.Extensions.DependencyInjection` 3.1.1 in a Xamarin.Mac Modern project and NuKeeper upgraded it to 3.1.2, which caused it to fail at runtime.

`Microsoft.Extensions.DependencyInjection` has both netstandard20 and a netstandard21 target frameworks. The netstandard20 target famework has a dependency on `Microsoft.Bcl.AsyncInterfaces` 1.1.0

Visual Studio for Mac installed it with a `<HintPath>` of `netstandard2.1`, which has been [compatible with Xamarin.Mac since 5.16](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

NuKeeper changed this `<HintPath>` of `netstandard2.0`, but left `Microsoft.Bcl.AsyncInterfaces` with its `<HintPath>` of `netstandard2.1` because that's still the latest version of that package.

### Expected behavior

- NuKeeper should maintain the current target framework in the hint path in the csproj.
- If it does need to change the target framework, it should also change the target framework of all of the dependencies.

### Reproduction steps

1. Create a new Xamarin.Mac project
2. Add `Microsoft.Extensions.DependencyInjection` 3.1.1 using Visual Studio for Mac
3. Add `Microsoft.Bcl.AsyncInterfaces` 1.1.0 using Visual Studio for Mac
4. `using Microsoft.Extensions.DependencyInjection; new ServiceCollection().BuildServiceProvider();`
5. Use NuKeeper to upgrade Microsoft.Extensions.DependencyInjection to 3.1.2, while leaving `Microsoft.Bcl.AsyncInterfaces` at 1.1.0

### Configuration

**Version:** 0.26.1

**Platform if applicable:** 
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [x] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by AnthonySteele** [comment]
Hm, nukeeper will just call out to `dotnet` in order to do the update. Why would `dotnet` get it wrong?
