### ISSUE TITLE
Support Project SDK versioning

### ISSUE THREAD

**Issue by ianjirka** [NuKeeperDotNet/NuKeeper#928]
## 🚀 Feature Requests

NuGet can be used to resolve MSBuild project SDKs.  The NuGet resolver is included by default.  For more details, see here:
https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019

### Contextualize the feature
NuKeeper already manages NuGet dependencies for code - the same logic can apply to other uses of NuKeeper.  Much of the update logic will be the same.  The purpose is the same, especially since NuGet resolved SDK dependencies must have a version number specified, 

### Describe the feature
NuKeeper updates Project SDKs that are resolved via NuGet in the exact same manner as code dependencies.

The following forms should be supported:
<Project Sdk="My.Custom.Sdk/1.2.3">
    ...
</Project>

<Project>
    <Sdk Name="My.Custom.Sdk" Version="1.2.3" />
    ...
</Project>

Since Versions are required for the NuGet resolver, only those with explicit versions need be considered.
If a package cannot be located in a configured NuGet feed it can be ignored with an informational log since it may be resolved via other mechanism.  

### Platforms affected (mark all that apply)
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

I did not mark anything because this should not be specific to any platform.

**Comment by CrispyDrone** [comment]
@ianjirka

A few questions in terms of the added value of this feature for nukeeper:

1. How often are new versions released for an sdk?
2. Is it "important" that you update to the newest versions at all times? Compare with patch releases for libraries.
