### ISSUE TITLE
Flaw with age filter

### ISSUE THREAD

**Issue by bogie129** [NuKeeperDotNet/NuKeeper#931]
There is a flaw in how the age filtering fundamentally works.

Scenario:

Lets take a package that is on a frequent release cycle and releases an update, regardless of the major/minor/patch construct, every week of the year.  Now lets assume that as a consumer I want to only integrate packages that have been available for at least 14 days.

The way the logic in nukeeper works is that it source all available upgrades for a package and orders them based on version.  It than proceeds to determine which of those package would satisfy an upgrade condition for Major/Minor/Patch filter criteria and brings back ONLY those three possibilities.  From there based on the filter choice it determines if one of these three sourced version qualify for upgrade based on age.

When consuming a fast paced project, like AWS SDKs, unless you are willing to take the latest bleeding edge version, nukeeper will never spot packages for upgrade.  

Solution:

The age filtering criteria has to be shifted into the VersionChanges class where metadata for all versions of a package are retrieved.  From there the date filter should FIRST be applied, followed by the determining whether packages that qualify based on date now qualify based on Major/Minor/Patch exclusion list.

**Comment by buildcomplete** [comment]
Interesting issue, I came here to report another, namely that when using the inspect parameter, nukeeper completely ignored the age field, but from what you write I cannot use it at all
