### ISSUE TITLE
How do I get this running with GitHub Actions?

### ISSUE THREAD

**Issue by ffMathy** [NuKeeperDotNet/NuKeeper#934]
Would be cool if there was a GitHub Action that could be used with this, or at least instructions on how to do it, with a `schedule` trigger.

**Comment by zubivan** [comment]
Hi @ffMathy, can you try https://github.com/NuKeeperDotNet/NuKeeper-Action and see if it works for you. I'd call it an alpha at the moment, we're still pretty new to github actions and experimenting here. Let me know if that works for you!
