### ISSUE TITLE
No handling of termination/abort signals - ctrl-z or ctrl-c

### ISSUE THREAD

**Issue by ransagy** [NuKeeperDotNet/NuKeeper#937]
## 🐛 Bug Report

NuKeeper doesn't seem to respond or handle termination signals such as ctrl+c and ctrl+z as defined by shell standards. The keypresses are ignored and NuKeeper continues to do its work regardless.

Specifically tried on WIndows 10 in cmd, powershell and both of these via Windows Terminal too (if that matters).

### Expected behavior

Upon sending a termination signal (SIGTERM/SIGINT) NuKeeper stops its processing, gracefully or not.

### Reproduction steps

Run any NuKeeper command (i.e. nukeeper update, nukeeper inspect etc).
Press Ctrl+C/Ctrl+Z (depending on OS and shell)

### Configuration

**Version:** 0.26.1

**Platform if applicable:** 
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by ransagy** [comment]
Anyone has any direction i could look at here, in terms o the code base?
I've been bitten by this enough to take a look even with the relatively small amount of free time i have, But would need some direction first.

**Comment by CrispyDrone** [comment]
@ransagy 

What I meant was, are you starting the processes in any specific way? Look at this issue for example: https://github.com/microsoft/terminal/issues/5460

In this case windows terminal was started using `cmd /c start /b wt` which would cause issues since the windows terminal process would inherit the disabled flag for ctrl+c.

**Comment by ransagy** [comment]
Nope, straight up Run/Start Menu launching.
I think it's most notable during actual inspection/updates, maybe when external processes are involved.

**Comment by CrispyDrone** [comment]
Ok, great. 

I think that makes sense. I don't think the way the invocation of external processes is written right now allows for cancellation.
