### ISSUE TITLE
Auto Complete Pull Requests

### ISSUE THREAD

**Issue by pyrostew** [NuKeeperDotNet/NuKeeper#938]
## 🚀 Feature Requests

Setting the Auto Complete option on PRs when creating them, to allow for fully autonomous integration of packages updates.

### Contextualize the feature
The use case I am aiming for is where a given Repo consumes a large number of internally released packages provided as Dev drops, the repo should be built nightly with the latest packages producing a deplyoment Dev drop. This allows test teams to always have a fully up to date integrated deployment package to put on the test environment, without having to have a developer approve changes every day.

### Describe the feature
Add an option called "--setAutoComplete" which sets the "autoCompleteSetBy" property on the PRRequest type when the option is provided. Ref [Microsoft Docs Pull Requests - Create](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/create?view=vsts-rest-tfs-4.1#request-body) 

Possibly expand to do something similar in GitHub, but I don't know how that would work.

### Platforms affected (mark all that apply)
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [x] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by pyrostew** [comment]
I see that @Berreek has done some work on this. Is there still any interest in progressing this?

**Comment by skolima** [comment]
In progress: https://github.com/NuKeeperDotNet/NuKeeper/pull/1005

**Comment by skolima** [comment]
Merged.
