### ISSUE TITLE
Nukeeper --inspect ignores --age 3d

### ISSUE THREAD

**Issue by buildcomplete** [NuKeeperDotNet/NuKeeper#939]
## 🐛 Bug Report

I am setting up nukeeper to update all our nuget packages, since we are using svn I use powershell to stitch everything together, I use nukeeper inspect to determine if I should update.

I ran into the following issue,
Nukeeper --inspect ignores --age 3d

for instance, 
the command:

    nukeeper inspect --age 3d --source http://urlto/FeedService.svc/ --include ^VM.

list changes that was just made,but

    nukeeper update --age 3d --source http://urlto/FeedService.svc/ --include ^VM.

list no changes (which is correct since I just updated and build new nuget packages)

according to the [documentation][1], the parameter **age** is applied to *all* commands

Note: I saw there is another bug with [age][2], until that is fixed probably have to set up with --age 0, which might be ok since it is only our own packages we update :) 

  [1]: https://github.com/NuKeeperDotNet/NuKeeper/wiki/Configuration
  [2]: https://github.com/NuKeeperDotNet/NuKeeper/issues/931
### Expected behavior
nukeeper inspect --age 3d --source http://urlto/FeedService.svc/ --include ^VM.
Do not list nuget newer than age

### Reproduction steps
nukeeper inspect --age 3d --source http://urlto/FeedService.svc/ --include ^VM.
lists, nuget newer than age

### Configuration

**Version:** 0.26.1

**Platform if applicable:** 
- [x ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CrispyDrone** [comment]
The `age` parameter is currently ignored in `inspect`'s implementation:

https://github.com/NuKeeperDotNet/NuKeeper/blob/4c71eeb80b8ac7686a319fd337df9ceb1315e718/NuKeeper/Local/LocalEngine.cs#L71-L76
