### ISSUE TITLE
Error with package and package dependency both updating

### ISSUE THREAD

**Issue by bacpcgus** [NuKeeperDotNet/NuKeeper#940]
## 🐛 Bug Report

This was also posted here (https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/issues/52) but I'm not sure that repo is the right place for this...

In our case, we have AbcPDF and AbcPDF.AbcGecko, which depends on AbcPdf.  Both are flagged as packages to update as seen here:

```
Updating 3 packages
'ABCpdf' from 11.3.04 to 11.3.7 in 1 projects
'ABCpdf.ABCGecko' from 11.3.04 to 11.3.7 in 1 projects
'IPNetwork2' from 2.5.189 to 2.5.192 in 1 projects

Git checkout 'origin/master'
Using branch name: 'nukeeper-update-3-packages-5522AB1B8600493317E2E4EAA554586C'
Git checkout new branch 'nukeeper-update-3-packages-5522AB1B8600493317E2E4EAA554586C'
Sorted 1 projects by dependencies but no change made
```

But then when NuKeeper updated AbcPDF, `Nuget.exe update` also updates AbcPDF.AbcGecko (I ran this locally using Nuget to confirm this is what happens):

```
Updating 'ABCpdf' to 11.3.7 in 1 projects
Nuget restore on D:\a\1\s\MyProject packages.config
Found NuGet.exe: C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe
In path D:\a\1\s\MyProject, running command: C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe restore packages.config -Source https://api.nuget.org/v3/index.json  -NonInteractive
Nuget restore on packages.config complete
Found NuGet.exe: C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe
In path D:\a\1\s\MyProject, running command: C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe update packages.config -Id ABCpdf -Version 11.3.7 -Source https://api.nuget.org/v3/index.json -NonInteractive
Git commit with message '📦 Automatic update of ABCpdf to 11.3.7'
```

But then NuKeeper doesn't know that AbcGecko was updated, and still attempts to explicitly update AbcPDF.AbcGecko (which, again, is already fully up-to-date from the AbcPDF update).  So `update` doesn't actually change the packages.config file.  And then NuKeeper attempts to create a commit, but nothing has changed and we get an exception and the whole thing fails:

```
Sorted 1 projects by dependencies but no change made
Updating 'ABCpdf.ABCGecko' to 11.3.7 in 1 projects
Nuget restore on D:\a\1\s\MyProject packages.config
In path D:\a\1\s\MyProject, running command: C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe restore packages.config -Source https://api.nuget.org/v3/index.json  -NonInteractive
Nuget restore on packages.config complete
Found NuGet.exe: C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe
In path D:\a\1\s\MyProject, running command: C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe update packages.config -Id ABCpdf -Version 11.3.7 -Source https://api.nuget.org/v3/index.json -NonInteractive
Git commit with message '📦 Automatic update of ABCpdf to 11.3.7'
Sorted 1 projects by dependencies but no change made
Updating 'ABCpdf.ABCGecko' to 11.3.7 in 1 projects
Nuget restore on D:\a\1\s\MyProject packages.config
In path D:\a\1\s\MyProject, running command: C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe restore packages.config -Source https://api.nuget.org/v3/index.json  -NonInteractive
Nuget restore on packages.config complete
In path D:\a\1\s\MyProject, running command: C:\hostedtoolcache\windows\nukeeper\0.26.0\x64\NuGet.exe update packages.config -Id ABCpdf.ABCGecko -Version 11.3.7 -Source https://api.nuget.org/v3/index.json -NonInteractive
Git commit with message '📦 Automatic update of ABCpdf.ABCGecko to 11.3.7'
Updates failed EmptyCommitException : No changes; nothing to commit.
   at LibGit2Sharp.Repository.Commit(String message, Signature author, Signature committer, CommitOptions options)
   at LibGit2Sharp.RepositoryExtensions.Commit(IRepository repository, String message, Signature author, Signature committer)
   at NuKeeper.Git.LibGit2SharpDriver.<>c__DisplayClass15_0.<Commit>b__0() in d:\a\r1\a\drop\NuKeeper.Git\LibGit2SharpDriver.cs:line 148
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in d:\a\r1\a\drop\NuKeeper\Engine\Packages\PackageUpdater.cs:line 82
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 updates, NuGetSources sources, SettingsContainer settings) in d:\a\r1\a\drop\NuKeeper\Engine\Packages\PackageUpdater.cs:line 46
Attempted 3 updates and did 0
Done at 2020-04-03T15:57:02Z
##[debug]task result: Succeeded
```

I feel like the easiest fix to this would be to simply not have an empty commit cause the whole thing to blow up.  But I suspect there's a bigger problem with dependencies at play here.

I'd also like to know if there's a workaround until a fix is completed and release made.

### Expected behavior
Updating multiple packages, including packages that depend on each other works without error.

### Reproduction steps
See above.

### Configuration
running NuKeeper task in an automated Azure DevOps build pipeline. 

**Version:** 0.26.0

**Platform if applicable:** 
- [X] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [X] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CrispyDrone** [comment]
A workaround right now could be to exclude the root dependency using `--exclude AbcPDF`. Nukeeper should then upgrade `AbcPDF.Gecko`, which would result in its dependency `AbcPDF` also being updated.

I'm a bit confused however by the behavior of nuget. I don't understand why updating `AbcPDF` would result in a package that depends _on it_ being updated. 

I can only find [documentation](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution) about the reverse scenario i.e. updating a package also results in all its dependencies being updated, which in this case would be: "Update `AbcPDF.Gecko`? We also need to update `AbcPDF` as `Abc.PDF.Gecko` needs `AbcPDF`'s latest version to work.".
