### ISSUE TITLE
Update to specific version

### ISSUE THREAD

**Issue by FJ-BBD** [NuKeeperDotNet/NuKeeper#941]
## 💬 Questions and Help
Hi, is it possible to update to a specific version for example if package x version 1.59 is available and I only want to update to version 1.56?

**Comment by sharpSteff** [comment]
I'm also looking forward to such a feature.

**Comment by CrispyDrone** [comment]
If you only want to update to 1.59, would it make sense to do this update manually, and then exclude this package using `--exclude <yourpackage>`?
