### ISSUE TITLE
Update Nuget Package Failed because URL to an interal Nuget Feed contains a Space

### ISSUE THREAD

**Issue by may82** [NuKeeperDotNet/NuKeeper#942]
## 🐛 Bug Report

We are happy that we found this tool. Our system configuration is special, so we encountered a rare error.

Our internal Nuget-Feed Link (e.g. http:\\tfs.local\Our%20Solution\_packaging/our-Feed/nuget/v3/index.json) contains a space. 

In line 36 (DotNetUpdatePackageCommand.cs) NuKeeper cut the Url in two parts (e.g. http:\\tfs.local\Our Solution\_packaging/our-Feed/nuget/v3/index.json) while executing "dotnet add" command. 

here is the part of the log (--verbosity D) before the exception is thrown: 
`Nuget restore on local.project.TestConsole.csproj complete
In path C:\tfs\OurSolution\local.project\Development\local.project.TestConsole, running command: dotnet restore local.project.TestConsole.csproj -s http://tfs.local/Our%20Solution/_packaging/our-Feed/nuget/v3/index.json
In path C:\tfs\OurSolution\local.project\Development\local.project.TestConsole, running command: dotnet remove local.project.TestConsole.csproj package local.package
In path C:\tfs\OurSolution\local.project\Development\local.project.TestConsole, running command: dotnet add local.project.TestConsole.csproj package local.package -v 1.0.4.209 -s http://tfs.local/Our Solution/_packaging/our-Feed/nuget/v3/index.json`

### Expected behavior

To add in line 36 masked quotes for parameter "-s" 

e.g. dotnet add local.project.TestConsole.csproj package local.package -v 1.0.4.209 -s **"**http://tfs.local/Our Solution/_packaging/our-Feed/nuget/v3/index.json**"**

**Comment by AnthonySteele** [comment]
What's interesting is that the `dotnet restore` part escapes the url. I assume that the `%20` escaping there is  correct and can be applied to the `dotnet add` part as well?

**Comment by AnthonySteele** [comment]
Should be fixed in latest release, can you verify?
