### ISSUE TITLE
PR description length may block merging

### ISSUE THREAD

**Issue by timmkrause** [NuKeeperDotNet/NuKeeper#985]
## 🐛 Bug Report

NuKeeper may produce pretty large pull request descriptions.

We are reaching the limits of Azure DevOps regarding description length sometimes when merging PRs.

![grafik](https://user-images.githubusercontent.com/2163179/82536413-b54e9c80-9b48-11ea-8b6b-8df2dad41000.png)

Side question: Is there a way to influence the description generation (or title generation)?

One way would be to add a limit for the maximum length which defaults to the currently allowed length by Azure DevOps and simply cut it from there and add ` [...]` at the end of the description.

I can imagine (!= I know) that this may be a quick fix and a low hanging fruit. Later on an option may be introduced to configure this (e.g. `--maxDescriptionLength {charCount/encodedLength}`).

One can argue that it should be an active decision by the user if it gets cut or not as others want to decide on their own what should be in the description and what should not. Then the mentioned option would be the way to go.

Another alternative would be to influence the description generation in some way, maybe via a template file?

### Expected behavior

Created pull requests should be mergable right away, at least via configuration.

### Configuration

**Version:** 0.27.1

**Platform if applicable:** 
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [x] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CrispyDrone** [comment]
A max length of 4000 has been present since at least version 0.20.1. I'm confused why this is not working for you.

I have a pull request open for customizing the templates for commit messages, pull request titles and bodies over [here](https://github.com/NuKeeperDotNet/NuKeeper/pull/1048).
