### ISSUE TITLE
Since 0.27.1 no Release Notes

### ISSUE THREAD

**Issue by zplan** [NuKeeperDotNet/NuKeeper#987]
## 💬 Questions and Help

Since version 0.27.1 there are no "Releases" and no Release notes anymore. But the releases are available on nuget.org.

Have the release notes location changed?

**Comment by AnthonySteele** [comment]
The issue seems to be that the integration is not firing, e.g. [here](https://dev.azure.com/nukeeper/NuKeeper/_releaseProgress?_a=release-environment-logs&releaseId=166&environmentId=168) 

> 2020-05-19T13:35:26.6507528Z ##[warning]Release will not be created as the tags for the target commit do not match with the given tag pattern
