### ISSUE TITLE
Multitarget support

### ISSUE THREAD

**Issue by bigdnf** [NuKeeperDotNet/NuKeeper#989]
## 🚀 Feature Requests

Multitarget support when executing nukeeper

### Contextualize the feature
Option when execute CLI to allow different behavior on different target when multitarget is used 

### Describe the feature
I have this king of configuration and I would like to address this in NuKeeper. Of course I could exclude those package but maybe it could be done by excluding specific target? Or maybe you have better idea - in this sample I have nothing to update in 3.1 but in other cases maybe there would be some packages that I will want to update but not touch those in 2.1 target.

```
<ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup Condition=" '$(TargetFramework)' != 'netcoreapp3.1'">
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.1" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.1" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="2.1.1" />
    </ItemGroup>

```

### Platforms affected (mark all that apply)
- [X ] :hammer_and_wrench: NuKeeper CLI

**Comment by CrispyDrone** [comment]
I think supporting this use case is too specific; I can imagine that there are many more conditions than just target framework that could result in requiring specific packages to be installed. I'm thinking of maybe feature flags so compiling with certain features enabled or not (I haven't personally worked on a project that had such a requirement, or supported something like this, so I'm sure other people might be able to come up with additional examples).

What would make sense in my opinion is to add extensibility points (hooks) in nukeeper where you would be able to modify for example, which packages actually end up getting selected. In your case, you would be able to write a hook for a target framework.

What do you think?

**Comment by dominikjeske** [comment]
Extensibility point sound good - I understand you don't want to handle each case.
ps. This case is obsolete for me now  becouse we now have only 3.1 ;)
